# N5 Kanji Seeder
# Data provided by user

puts "Seeding N5 Kanji Single..."

n5_kanji_data = [
  { rate: "N5", kanji: "日", kunyomi: "ひ／び、か", onyomi: "にち", meaning_id: "Matahari, hari", description_id: "Kanji dasar yang sangat sering digunakan untuk menyatakan hari, tanggal, dan matahari. Contoh: にちようび (hari Minggu), きょう (hari ini), にほん (Jepang)" },
  { rate: "N5", kanji: "月", kunyomi: "つき", onyomi: "げつ、がつ", meaning_id: "Bulan", description_id: "Digunakan untuk bulan dalam kalender dan nama-nama bulan. Contoh: いちがつ (Januari), げつようび (hari Senin), こんげつ (bulan ini)" },
  { rate: "N5", kanji: "木", kunyomi: "き、こ", onyomi: "もく、ぼく", meaning_id: "Pohon, kayu", description_id: "Kanji untuk pohon dan kayu, juga digunakan dalam hari Kamis. Contoh: もくようび (hari Kamis), きのした (bawah pohon), もくざい (kayu)" },
  { rate: "N5", kanji: "山", kunyomi: "やま", onyomi: "さん、ざん", meaning_id: "Gunung", description_id: "Kanji untuk gunung, sering muncul dalam nama gunung dan tempat. Contoh: ふじさん (Gunung Fuji), やまのぼり (mendaki gunung), やまみち (jalan gunung)" },
  { rate: "N5", kanji: "川", kunyomi: "かわ、がわ", onyomi: "せん", meaning_id: "Sungai", description_id: "Digunakan untuk sungai, sering muncul dalam nama tempat. Contoh: かわのみず (air sungai), たながわ (nama sungai), かわべ (tepi sungai)" },
  { rate: "N5", kanji: "田", kunyomi: "た、だ", onyomi: "でん", meaning_id: "Sawah", description_id: "Kanji untuk sawah, sering muncul dalam nama keluarga Jepang. Contoh: たなか (nama keluarga), でんしゃ (kereta api - dari 電車), たんぼ (sawah)" },
  { rate: "N5", kanji: "人", kunyomi: "ひと", onyomi: "じん、にん", meaning_id: "Orang, manusia", description_id: "Kanji fundamental untuk manusia, digunakan dalam banyak kata. Contoh: にほんじん (orang Jepang), ひとり (satu orang), だいじん (menteri)" },
  { rate: "N5", kanji: "口", kunyomi: "くち", onyomi: "こう、く", meaning_id: "Mulut", description_id: "Kanji untuk mulut, juga digunakan untuk lubang atau pintu masuk. Contoh: いりぐち (pintu masuk), でぐち (pintu keluar), じんこう (populasi)" },
  { rate: "N5", kanji: "車", kunyomi: "くるま", onyomi: "しゃ", meaning_id: "Mobil, kendaraan", description_id: "Kanji untuk kendaraan beroda, sangat umum dalam transportasi. Contoh: でんしゃ (kereta api), じどうしゃ (mobil), しゃりん (roda)" },
  { rate: "N5", kanji: "門", kunyomi: "もん", onyomi: "もん", meaning_id: "Gerbang, pintu", description_id: "Kanji untuk gerbang atau pintu besar, sering muncul dalam nama tempat. Contoh: せいもん (gerbang utama), もんばん (penjaga gerbang), もんだい (masalah)" },

  { rate: "N5", kanji: "火", kunyomi: "ひ", onyomi: "か", meaning_id: "Api", description_id: "Kanji untuk api, digunakan dalam hari Selasa dan hal-hal terkait api. Contoh: かようび (hari Selasa), かじ (kebakaran), はなび (kembang api)" },
  { rate: "N5", kanji: "水", kunyomi: "みず", onyomi: "すい", meaning_id: "Air", description_id: "Kanji untuk air, digunakan dalam hari Rabu dan berbagai kata terkait air. Contoh: すいようび (hari Rabu), みずうみ (danau), すいどう (saluran air)" },
  { rate: "N5", kanji: "金", kunyomi: "かね", onyomi: "きん、こん", meaning_id: "Emas, uang, logam", description_id: "Kanji untuk emas dan uang, juga hari Jumat. Contoh: きんようび (hari Jumat), おかね (uang), きんこ (brankas)" },
  { rate: "N5", kanji: "土", kunyomi: "つち", onyomi: "ど、と", meaning_id: "Tanah", description_id: "Kanji untuk tanah, digunakan dalam hari Sabtu dan hal-hal terkait tanah. Contoh: どようび (hari Sabtu), つち (tanah), こくど (wilayah negara)" },
  { rate: "N5", kanji: "子", kunyomi: "こ", onyomi: "し、す", meaning_id: "Anak", description_id: "Kanji untuk anak, sangat umum digunakan. Contoh: こども (anak-anak), おとこのこ (anak laki-laki), おんなのこ (anak perempuan)" },
  { rate: "N5", kanji: "女", kunyomi: "おんな", onyomi: "じょ、にょ", meaning_id: "Wanita, perempuan", description_id: "Kanji untuk perempuan, digunakan dalam berbagai kata terkait wanita. Contoh: じょせい (wanita), おんな (perempuan), じょし (gadis)" },
  { rate: "N5", kanji: "学", kunyomi: "まな（ぶ）", onyomi: "がく", meaning_id: "Belajar, ilmu", description_id: "Kanji fundamental untuk pendidikan dan pembelajaran. Contoh: がっこう (sekolah), だいがく (universitas), がくせい (siswa)" },
  { rate: "N5", kanji: "生", kunyomi: "い（きる）、う（まれる）、なま", onyomi: "せい、しょう", meaning_id: "Hidup, lahir, mentah", description_id: "Kanji serbaguna untuk kehidupan, kelahiran, dan siswa. Contoh: せんせい (guru), がくせい (siswa), いきもの (makhluk hidup)" },
  { rate: "N5", kanji: "先", kunyomi: "さき", onyomi: "せん", meaning_id: "Dulu, terdahulu", description_id: "Kanji untuk sebelumnya atau yang lebih dulu, sering digunakan dalam sopan santun. Contoh: せんせい (guru), せんぱい (senior), さきに (terlebih dahulu)" },
  { rate: "N5", kanji: "私", kunyomi: "わたし、わたくし", onyomi: "し", meaning_id: "Saya, pribadi", description_id: "Kanji untuk 'saya' dalam bentuk formal dan sopan. Contoh: わたし (saya), しりつ (swasta), ししゃ (pribadi)" },

  { rate: "N5", kanji: "一", kunyomi: "ひと（つ）", onyomi: "いち、いつ", meaning_id: "Satu", description_id: "Angka satu, kanji paling dasar untuk berhitung. Contoh: いちにち (satu hari), いちど (sekali), いっぽん (satu batang)" },
  { rate: "N5", kanji: "二", kunyomi: "ふた（つ）", onyomi: "に", meaning_id: "Dua", description_id: "Angka dua, digunakan dalam berhitung dan tanggal. Contoh: ふつか (tanggal dua), にかい (lantai dua), ふたり (dua orang)" },
  { rate: "N5", kanji: "三", kunyomi: "みっ（つ）", onyomi: "さん", meaning_id: "Tiga", description_id: "Angka tiga, digunakan dalam berhitung dan waktu. Contoh: みっか (tanggal tiga), さんじ (jam tiga), みつ (tiga buah)" },
  { rate: "N5", kanji: "四", kunyomi: "よっ（つ）、よん", onyomi: "し、よん", meaning_id: "Empat", description_id: "Angka empat, sering dihindari karena homonim dengan 'mati'. Contoh: よっか (tanggal empat), よじ (jam empat), しがつ (bulan April)" },
  { rate: "N5", kanji: "五", kunyomi: "いつ（つ）", onyomi: "ご", meaning_id: "Lima", description_id: "Angka lima, digunakan dalam berhitung dan waktu. Contoh: いつか (tanggal lima), ごじ (jam lima), ごがつ (bulan Mei)" },
  { rate: "N5", kanji: "六", kunyomi: "むっ（つ）", onyomi: "ろく", meaning_id: "Enam", description_id: "Angka enam, digunakan dalam berhitung dan waktu. Contoh: むいか (tanggal enam), ろくじ (jam enam), ろくがつ (bulan Juni)" },
  { rate: "N5", kanji: "七", kunyomi: "なな（つ）、なの", onyomi: "しち、なな", meaning_id: "Tujuh", description_id: "Angka tujuh, memiliki dua cara baca yang umum. Contoh: なのか (tanggal tujuh), しちじ (jam tujuh), しちがつ (bulan Juli)" },
  { rate: "N5", kanji: "八", kunyomi: "やっ（つ）", onyomi: "はち", meaning_id: "Delapan", description_id: "Angka delapan, dianggap angka keberuntungan. Contoh: ようか (tanggal delapan), はちじ (jam delapan), はちがつ (bulan Agustus)" },
  { rate: "N5", kanji: "九", kunyomi: "ここの（つ）", onyomi: "きゅう、く", meaning_id: "Sembilan", description_id: "Angka sembilan, sering dihindari karena homonim dengan 'penderitaan'. Contoh: ここのか (tanggal sembilan), くじ (jam sembilan), くがつ (bulan September)" },
  { rate: "N5", kanji: "十", kunyomi: "とお", onyomi: "じゅう", meaning_id: "Sepuluh", description_id: "Angka sepuluh, dasar sistem bilangan Jepang. Contoh: とおか (tanggal sepuluh), じゅうじ (jam sepuluh), じゅうがつ (bulan Oktober)" },
  { rate: "N5", kanji: "百", kunyomi: "-", onyomi: "ひゃく", meaning_id: "Seratus", description_id: "Angka seratus, digunakan dalam bilangan besar. Contoh: ひゃくえん (100 yen), さんびゃく (300), ひゃっか (berbagai macam)" },
  { rate: "N5", kanji: "千", kunyomi: "-", onyomi: "せん", meaning_id: "Seribu", description_id: "Angka seribu, digunakan dalam bilangan besar. Contoh: せんえん (1000 yen), さんぜん (3000), せんねん (seribu tahun)" },
  { rate: "N5", kanji: "万", kunyomi: "-", onyomi: "まん、ばん", meaning_id: "Sepuluh ribu", description_id: "Angka sepuluh ribu, unit besar dalam sistem bilangan Jepang. Contoh: いちまんえん (10.000 yen), ばんざい (banzai), まんねん (sepuluh ribu tahun)" },
  { rate: "N5", kanji: "円", kunyomi: "-", onyomi: "えん", meaning_id: "Yen (mata uang), lingkaran", description_id: "Mata uang Jepang dan bentuk lingkaran. Contoh: ひゃくえん (100 yen), えんけい (bentuk lingkaran), まるい (bulat)" },
  { rate: "N5", kanji: "年", kunyomi: "とし", onyomi: "ねん", meaning_id: "Tahun", description_id: "Kanji untuk tahun, sangat penting dalam menyatakan waktu. Contoh: らいねん (tahun depan), ことし (tahun ini), ねんれい (umur)" },

  { rate: "N5", kanji: "上", kunyomi: "うえ、あ（がる）、のぼ（る）", onyomi: "じょう、しょう", meaning_id: "Atas, naik", description_id: "Kanji untuk atas dan naik, digunakan dalam berbagai konteks arah. Contoh: うえ (atas), じょうず (pandai), のぼる (naik)" },
  { rate: "N5", kanji: "下", kunyomi: "した、さ（がる）、くだ（る）", onyomi: "か、げ", meaning_id: "Bawah, turun", description_id: "Kanji untuk bawah dan turun, kebalikan dari 上. Contoh: した (bawah), げた (geta), さがる (turun)" },
  { rate: "N5", kanji: "中", kunyomi: "なか", onyomi: "ちゅう", meaning_id: "Tengah, dalam", description_id: "Kanji untuk tengah dan dalam, sangat sering digunakan. Contoh: なか (dalam), ちゅうがく (SMP), にほんちゅう (seluruh Jepang)" },
  { rate: "N5", kanji: "大", kunyomi: "おお（きい）", onyomi: "だい、たい", meaning_id: "Besar", description_id: "Kanji untuk besar, digunakan dalam berbagai kata positif. Contoh: おおきい (besar), だいがく (universitas), たいせつ (penting)" },
  { rate: "N5", kanji: "小", kunyomi: "ちい（さい）、こ、お", onyomi: "しょう", meaning_id: "Kecil", description_id: "Kanji untuk kecil, kebalikan dari 大. Contoh: ちいさい (kecil), しょうがく (SD), こがた (ukuran kecil)" },
  { rate: "N5", kanji: "本", kunyomi: "もと", onyomi: "ほん、ぽん", meaning_id: "Buku, asal, batang", description_id: "Kanji serbaguna untuk buku, asal, dan penghitung benda panjang. Contoh: ほん (buku), にほん (Jepang), いっぽん (satu batang)" },
  { rate: "N5", kanji: "半", kunyomi: "なか（ば）", onyomi: "はん", meaning_id: "Setengah", description_id: "Kanji untuk setengah, digunakan dalam waktu dan ukuran. Contoh: はんぶん (setengah), はんじ (setengah jam), ぜんはん (paruh pertama)" },
  { rate: "N5", kanji: "分", kunyomi: "わ（ける）、わ（かる）", onyomi: "ぶん、ふん、ぷん", meaning_id: "Bagian, menit, memahami", description_id: "Kanji untuk menit dan bagian, sangat penting dalam waktu. Contoh: いっぷん (satu menit), ぶんせき (analisis), はんぶん (setengah)" },
  { rate: "N5", kanji: "力", kunyomi: "ちから", onyomi: "りょく、りき", meaning_id: "Kekuatan, tenaga", description_id: "Kanji untuk kekuatan fisik dan mental. Contoh: ちから (kekuatan), どりょく (usaha), のうりょく (kemampuan)" },
  { rate: "N5", kanji: "何", kunyomi: "なに、なん", onyomi: "か", meaning_id: "Apa", description_id: "Kanji untuk 'apa', kata tanya yang sangat penting. Contoh: なに (apa), なんじ (jam berapa), なんにん (berapa orang)" },

  { rate: "N5", kanji: "明", kunyomi: "あか（るい）、あ（ける）", onyomi: "めい、みょう", meaning_id: "Terang, cerah", description_id: "Kanji untuk terang dan jelas, sering digunakan dalam nama. Contoh: あかるい (terang), せつめい (penjelasan), あした (besok)" },
  { rate: "N5", kanji: "休", kunyomi: "やす（む）", onyomi: "きゅう", meaning_id: "Istirahat", description_id: "Kanji untuk istirahat dan libur. Contoh: やすみ (libur), きゅうけい (istirahat), やすむ (beristirahat)" },
  { rate: "N5", kanji: "体", kunyomi: "からだ", onyomi: "たい、てい", meaning_id: "Tubuh, badan", description_id: "Kanji untuk tubuh dan badan. Contoh: からだ (tubuh), たいいく (olahraga), ぜんたい (keseluruhan)" },
  { rate: "N5", kanji: "好", kunyomi: "す（く）、この（む）", onyomi: "こう", meaning_id: "Suka, baik", description_id: "Kanji untuk suka dan kesukaan. Contoh: すき (suka), こうき (rasa ingin tahu), あいこう (kasih sayang)" },
  { rate: "N5", kanji: "男", kunyomi: "おとこ", onyomi: "だん、なん", meaning_id: "Laki-laki, pria", description_id: "Kanji untuk laki-laki dan pria. Contoh: おとこ (laki-laki), だんせい (pria), だんし (anak laki-laki)" },
  { rate: "N5", kanji: "林", kunyomi: "はやし", onyomi: "りん", meaning_id: "Hutan kecil", description_id: "Kanji untuk hutan kecil, sering muncul dalam nama keluarga. Contoh: はやし (hutan kecil), しんりん (hutan), こばやし (nama keluarga)" },
  { rate: "N5", kanji: "森", kunyomi: "もり", onyomi: "しん", meaning_id: "Hutan", description_id: "Kanji untuk hutan besar. Contoh: もり (hutan), しんりん (hutan), もりもり (subur)" },
  { rate: "N5", kanji: "間", kunyomi: "あいだ、ま", onyomi: "かん、けん", meaning_id: "Antara, waktu", description_id: "Kanji untuk waktu dan ruang di antara. Contoh: あいだ (antara), じかん (waktu), にんげん (manusia)" },
  { rate: "N5", kanji: "畑", kunyomi: "はたけ、はた", onyomi: "-", meaning_id: "Ladang", description_id: "Kanji untuk ladang tanaman kering. Contoh: はたけ (ladang), のうか (petani), やさい (sayuran)" },
  { rate: "N5", kanji: "岩", kunyomi: "いわ", onyomi: "がん", meaning_id: "Batu besar, karang", description_id: "Kanji untuk batu besar dan karang. Contoh: いわ (batu besar), がんせき (batu karang), いわば (seperti)" },

  { rate: "N5", kanji: "目", kunyomi: "め", onyomi: "もく、ぼく", meaning_id: "Mata", description_id: "Kanji untuk mata dan melihat. Contoh: め (mata), もくてき (tujuan), ちゅうもく (perhatian)" },
  { rate: "N5", kanji: "耳", kunyomi: "みみ", onyomi: "じ", meaning_id: "Telinga", description_id: "Kanji untuk telinga dan mendengar. Contoh: みみ (telinga), みみざわり (tidak enak didengar)" },
  { rate: "N5", kanji: "手", kunyomi: "て", onyomi: "しゅ", meaning_id: "Tangan", description_id: "Kanji untuk tangan dan melakukan. Contoh: て (tangan), てつだい (membantu), しゅだん (cara)" },
  { rate: "N5", kanji: "足", kunyomi: "あし", onyomi: "そく", meaning_id: "Kaki, cukup", description_id: "Kanji untuk kaki dan cukup. Contoh: あし (kaki), そくど (kecepatan), まんぞく (puas)" },
  { rate: "N5", kanji: "雨", kunyomi: "あめ", onyomi: "う", meaning_id: "Hujan", description_id: "Kanji untuk hujan dan cuaca. Contoh: あめ (hujan), うてん (cuaca buruk), あまぐも (awan hujan)" },
  { rate: "N5", kanji: "竹", kunyomi: "たけ", onyomi: "ちく", meaning_id: "Bambu", description_id: "Kanji untuk bambu. Contoh: たけ (bambu), ちくりん (hutan bambu), たけのこ (rebung)" },
  { rate: "N5", kanji: "米", kunyomi: "こめ", onyomi: "べい、まい", meaning_id: "Beras, nasi", description_id: "Kanji untuk beras, makanan pokok Jepang. Contoh: こめ (beras), べいこく (Amerika), こめつぶ (butir beras)" },
  { rate: "N5", kanji: "貝", kunyomi: "かい", onyomi: "ばい", meaning_id: "Kerang", description_id: "Kanji untuk kerang, sering digunakan dalam kanji terkait uang. Contoh: かい (kerang), かいがら (cangkang kerang)" },
  { rate: "N5", kanji: "石", kunyomi: "いし", onyomi: "せき、しゃく", meaning_id: "Batu", description_id: "Kanji untuk batu dan mineral. Contoh: いし (batu), せきゆ (minyak bumi), いしやき (panggang batu)" },
  { rate: "N5", kanji: "糸", kunyomi: "いと", onyomi: "し", meaning_id: "Benang", description_id: "Kanji untuk benang dan kain. Contoh: いと (benang), けいと (benang wol), ししゅう (sulaman)" },

  { rate: "N5", kanji: "花", kunyomi: "はな", onyomi: "か", meaning_id: "Bunga", description_id: "Kanji untuk bunga dan indah. Contoh: はな (bunga), かびん (vas bunga), はなみ (melihat bunga)" },
  { rate: "N5", kanji: "茶", kunyomi: "ちゃ", onyomi: "ちゃ、さ", meaning_id: "Teh", description_id: "Kanji untuk teh, budaya penting Jepang. Contoh: ちゃ (teh), おちゃ (teh), さどう (upacara teh)" },
  { rate: "N5", kanji: "肉", kunyomi: "にく", onyomi: "にく", meaning_id: "Daging", description_id: "Kanji untuk daging dan otot. Contoh: にく (daging), きんにく (otot), にくや (toko daging)" },
  { rate: "N5", kanji: "文", kunyomi: "-", onyomi: "ぶん、もん", meaning_id: "Tulisan, sastra", description_id: "Kanji untuk tulisan dan sastra. Contoh: ぶんしょう (kalimat), ぶんがく (sastra), もんじ (huruf)" },
  { rate: "N5", kanji: "字", kunyomi: "-", onyomi: "じ", meaning_id: "Huruf, karakter", description_id: "Kanji untuk huruf dan karakter. Contoh: もじ (huruf), かんじ (kanji), じしょ (kamus)" },
  { rate: "N5", kanji: "物", kunyomi: "もの", onyomi: "ぶつ、もつ", meaning_id: "Benda, hal", description_id: "Kanji untuk benda dan hal. Contoh: もの (benda), どうぶつ (hewan), たべもの (makanan)" },
  { rate: "N5", kanji: "牛", kunyomi: "うし", onyomi: "ぎゅう", meaning_id: "Sapi", description_id: "Kanji untuk sapi dan ternak. Contoh: うし (sapi), ぎゅうにく (daging sapi), ぎゅうにゅう (susu sapi)" },
  { rate: "N5", kanji: "馬", kunyomi: "うま", onyomi: "ば、ま", meaning_id: "Kuda", description_id: "Kanji untuk kuda. Contoh: うま (kuda), ばしゃ (kereta kuda), じょうば (berkuda)" },
  { rate: "N5", kanji: "鳥", kunyomi: "とり", onyomi: "ちょう", meaning_id: "Burung", description_id: "Kanji untuk burung. Contoh: とり (burung), やきとり (ayam bakar), にわとり (ayam)" },
  { rate: "N5", kanji: "魚", kunyomi: "さかな、うお", onyomi: "ぎょ", meaning_id: "Ikan", description_id: "Kanji untuk ikan dan makanan laut. Contoh: さかな (ikan), きんぎょ (ikan mas), さかなや (toko ikan)" },

  { rate: "N5", kanji: "新", kunyomi: "あたら（しい）、あら（た）", onyomi: "しん", meaning_id: "Baru", description_id: "Kanji untuk baru dan segar. Contoh: あたらしい (baru), しんぶん (koran), しんせん (segar)" },
  { rate: "N5", kanji: "古", kunyomi: "ふる（い）", onyomi: "こ", meaning_id: "Lama, kuno", description_id: "Kanji untuk lama dan kuno. Contoh: ふるい (lama), こだい (zaman kuno), ちゅうこ (bekas)" },
  { rate: "N5", kanji: "長", kunyomi: "なが（い）", onyomi: "ちょう", meaning_id: "Panjang, kepala", description_id: "Kanji untuk panjang dan pemimpin. Contoh: ながい (panjang), せんせい (guru), かいちょう (ketua)" },
  { rate: "N5", kanji: "短", kunyomi: "みじか（い）", onyomi: "たん", meaning_id: "Pendek", description_id: "Kanji untuk pendek. Contoh: みじかい (pendek), たんじかん (waktu singkat), たんぱん (celana pendek)" },
  { rate: "N5", kanji: "高", kunyomi: "たか（い）", onyomi: "こう", meaning_id: "Tinggi, mahal", description_id: "Kanji untuk tinggi dan mahal. Contoh: たかい (tinggi/mahal), こうこう (SMA), さいこう (tertinggi)" },
  { rate: "N5", kanji: "安", kunyomi: "やす（い）", onyomi: "あん", meaning_id: "Murah, aman", description_id: "Kanji untuk murah dan aman. Contoh: やすい (murah), あんぜん (aman), ふあん (cemas)" },
  { rate: "N5", kanji: "低", kunyomi: "ひく（い）", onyomi: "てい", meaning_id: "Rendah", description_id: "Kanji untuk rendah. Contoh: ひくい (rendah), ていおん (suhu rendah), さいてい (terendah)" },
  { rate: "N5", kanji: "暗", kunyomi: "くら（い）", onyomi: "あん", meaning_id: "Gelap", description_id: "Kanji untuk gelap dan suram. Contoh: くらい (gelap), あんき (menghafal), やみ (kegelapan)" },
  { rate: "N5", kanji: "多", kunyomi: "おお（い）", onyomi: "た", meaning_id: "Banyak", description_id: "Kanji untuk banyak dan sering. Contoh: おおい (banyak), たすう (mayoritas), おおく (banyak)" },
  { rate: "N5", kanji: "少", kunyomi: "すく（ない）、すこ（し）", onyomi: "しょう", meaning_id: "Sedikit", description_id: "Kanji untuk sedikit dan muda. Contoh: すくない (sedikit), しょうねん (remaja), すこし (sedikit)" },

  { rate: "N5", kanji: "行", kunyomi: "い（く）、おこな（う）", onyomi: "こう、ぎょう", meaning_id: "Pergi, baris", description_id: "Kanji untuk pergi dan baris. Contoh: いく (pergi), りょこう (perjalanan), ぎんこう (bank)" },
  { rate: "N5", kanji: "来", kunyomi: "く（る）、き（たる）", onyomi: "らい", meaning_id: "Datang", description_id: "Kanji untuk datang dan akan datang. Contoh: くる (datang), らいねん (tahun depan), みらい (masa depan)" },
  { rate: "N5", kanji: "帰", kunyomi: "かえ（る）", onyomi: "き", meaning_id: "Pulang, kembali", description_id: "Kanji untuk pulang dan kembali. Contoh: かえる (pulang), きこく (pulang ke negara asal)" },
  { rate: "N5", kanji: "食", kunyomi: "た（べる）、く（う）", onyomi: "しょく", meaning_id: "Makan, makanan", description_id: "Kanji untuk makan dan makanan. Contoh: たべる (makan), しょくじ (makan), しょくりょう (bahan makanan)" },
  { rate: "N5", kanji: "飲", kunyomi: "の（む）", onyomi: "いん", meaning_id: "Minum", description_id: "Kanji untuk minum. Contoh: のむ (minum), いんりょう (minuman), のみもの (minuman)" },
  { rate: "N5", kanji: "見", kunyomi: "み（る）", onyomi: "けん", meaning_id: "Melihat", description_id: "Kanji untuk melihat dan pandangan. Contoh: みる (melihat), けんがく (kunjungan studi), はっけん (penemuan)" },
  { rate: "N5", kanji: "聞", kunyomi: "き（く）", onyomi: "ぶん、もん", meaning_id: "Mendengar", description_id: "Kanji untuk mendengar dan bertanya. Contoh: きく (mendengar), しんぶん (koran), うわさ (gosip)" },
  { rate: "N5", kanji: "読", kunyomi: "よ（む）", onyomi: "どく、とく", meaning_id: "Membaca", description_id: "Kanji untuk membaca. Contoh: よむ (membaca), どくしょ (membaca buku), どっかい (pemahaman bacaan)" },
  { rate: "N5", kanji: "書", kunyomi: "か（く）", onyomi: "しょ", meaning_id: "Menulis, buku", description_id: "Kanji untuk menulis dan buku. Contoh: かく (menulis), としょかん (perpustakaan), しょさい (ruang baca)" },
  { rate: "N5", kanji: "話", kunyomi: "はな（す）、はなし", onyomi: "わ", meaning_id: "Berbicara, cerita", description_id: "Kanji untuk berbicara dan cerita. Contoh: はなす (berbicara), でんわ (telepon), はなし (cerita)" },
  { rate: "N5", kanji: "買", kunyomi: "か（う）", onyomi: "ばい", meaning_id: "Membeli", description_id: "Kanji untuk membeli. Contoh: かう (membeli), かいもの (belanja), こうばい (jual beli)" },
  { rate: "N5", kanji: "教", kunyomi: "おし（える）", onyomi: "きょう", meaning_id: "Mengajar", description_id: "Kanji untuk mengajar dan agama. Contoh: おしえる (mengajar), きょうしつ (ruang kelas), しゅうきょう (agama)" },

  { rate: "N5", kanji: "朝", kunyomi: "あさ", onyomi: "ちょう", meaning_id: "Pagi", description_id: "Kanji untuk pagi hari. Contoh: あさ (pagi), まいあさ (setiap pagi), ちょうしょく (sarapan)" },
  { rate: "N5", kanji: "昼", kunyomi: "ひる", onyomi: "ちゅう", meaning_id: "Siang", description_id: "Kanji untuk siang hari. Contoh: ひる (siang), ひるま (siang hari), ちゅうしょく (makan siang)" },
  { rate: "N5", kanji: "夜", kunyomi: "よる、よ", onyomi: "や", meaning_id: "Malam", description_id: "Kanji untuk malam hari. Contoh: よる (malam), まいばん (setiap malam), やしょく (makan malam)" },
  { rate: "N5", kanji: "晩", kunyomi: "ばん", onyomi: "ばん", meaning_id: "Malam (waktu makan)", description_id: "Kanji untuk malam dan sore. Contoh: ばん (malam), ばんごはん (makan malam), こんばん (malam ini)" },
  { rate: "N5", kanji: "夕", kunyomi: "ゆう", onyomi: "せき", meaning_id: "Senja", description_id: "Kanji untuk senja dan sore. Contoh: ゆうがた (sore), ゆうひ (matahari terbenam), ゆうしょく (makan malam)" },
  { rate: "N5", kanji: "方", kunyomi: "かた、ほう", onyomi: "ほう", meaning_id: "Arah, cara, orang", description_id: "Kanji untuk arah dan cara. Contoh: かた (cara), ほうこう (arah), かたほう (salah satu)" },
  { rate: "N5", kanji: "午", kunyomi: "-", onyomi: "ご", meaning_id: "Tengah hari", description_id: "Kanji untuk siang dan waktu. Contoh: ごぜん (AM), ごご (PM), しょうご (siang)" },
  { rate: "N5", kanji: "前", kunyomi: "まえ", onyomi: "ぜん", meaning_id: "Depan, sebelum", description_id: "Kanji untuk depan dan sebelum. Contoh: まえ (depan), ぜんかい (sebelumnya), ごぜん (AM)" },
  { rate: "N5", kanji: "後", kunyomi: "あと、うし（ろ）", onyomi: "ご、こう", meaning_id: "Belakang, setelah", description_id: "Kanji untuk belakang dan setelah. Contoh: あと (setelah), のち (kemudian), ごご (PM)" },
  { rate: "N5", kanji: "毎", kunyomi: "-", onyomi: "まい", meaning_id: "Setiap", description_id: "Kanji untuk setiap dan selalu. Contoh: まいにち (setiap hari), まいつき (setiap bulan), まいしゅう (setiap minggu)" },
  { rate: "N5", kanji: "週", kunyomi: "-", onyomi: "しゅう", meaning_id: "Minggu", description_id: "Kanji untuk minggu. Contoh: しゅう (minggu), らいしゅう (minggu depan), しゅうまつ (akhir pekan)" },
  { rate: "N5", kanji: "曜", kunyomi: "-", onyomi: "よう", meaning_id: "Hari (dalam seminggu)", description_id: "Kanji untuk hari dalam seminggu. Contoh: ようび (hari), なんようび (hari apa), どようび (Sabtu)" },

  { rate: "N5", kanji: "作", kunyomi: "つく（る）", onyomi: "さく、さ", meaning_id: "Membuat, karya", description_id: "Kanji untuk membuat atau karya, sering digunakan dalam konteks kreatif dan pekerjaan. Contoh: さくひん (karya), さくしゃ (penulis), つくる (membuat)" },
  { rate: "N5", kanji: "泳", kunyomi: "およ（ぐ）", onyomi: "えい", meaning_id: "Berenang", description_id: "Kanji untuk berenang, khusus digunakan dalam aktivitas air. Contoh: すいえい (renang), およぐ (berenang), へいえい (renang gaya dada)" },
  { rate: "N5", kanji: "油", kunyomi: "あぶら", onyomi: "ゆ", meaning_id: "Minyak", description_id: "Kanji untuk minyak, digunakan dalam konteks memasak dan industri. Contoh: あぶら (minyak), せきゆ (minyak bumi), しょうゆ (kecap asin)" },
  { rate: "N5", kanji: "海", kunyomi: "うみ", onyomi: "かい", meaning_id: "Laut", description_id: "Kanji untuk laut, sangat penting dalam geografi Jepang sebagai negara kepulauan. Contoh: うみ (laut), かいがん (pantai), にほんかい (Laut Jepang)" },
  { rate: "N5", kanji: "酒", kunyomi: "さけ、さか", onyomi: "しゅ", meaning_id: "Sake, minuman beralkohol", description_id: "Kanji untuk alkohol, terutama sake tradisional Jepang. Contoh: さけ (sake), びーる (bir), にほんしゅ (sake Jepang)" },
  { rate: "N5", kanji: "待", kunyomi: "ま（つ）", onyomi: "たい", meaning_id: "Menunggu", description_id: "Kanji untuk menunggu, sering digunakan dalam situasi sehari-hari. Contoh: まつ (menunggu), たいき (menunggu), きたい (harapan)" },
  { rate: "N5", kanji: "校", kunyomi: "-", onyomi: "こう", meaning_id: "Sekolah", description_id: "Kanji untuk sekolah, sangat penting dalam sistem pendidikan. Contoh: がっこう (sekolah), こうちょう (kepala sekolah), ぼしこう (sekolah ibu)" },
  { rate: "N5", kanji: "時", kunyomi: "とき", onyomi: "じ", meaning_id: "Waktu, jam", description_id: "Kanji untuk waktu dan jam, fundamental dalam kehidupan sehari-hari. Contoh: じかん (waktu), いちじ (jam satu), どうじ (pada saat yang sama)" },
  { rate: "N5", kanji: "言", kunyomi: "い（う）、こと", onyomi: "げん、ごん", meaning_id: "Berkata, kata", description_id: "Kanji untuk berkata atau bahasa, dasar komunikasi. Contoh: いう (berkata), げんご (bahasa), でんごん (pesan)" },
  { rate: "N5", kanji: "計", kunyomi: "はか（る）", onyomi: "けい", meaning_id: "Menghitung, rencana", description_id: "Kanji untuk menghitung atau rencana, digunakan dalam matematika dan bisnis. Contoh: けいさん (perhitungan), とけい (jam), けいかく (rencana)" },
  { rate: "N5", kanji: "語", kunyomi: "かた（る）", onyomi: "ご", meaning_id: "Bahasa, bercerita", description_id: "Kanji untuk bahasa atau kata, sering digunakan dalam pembelajaran bahasa. Contoh: にほんご (bahasa Jepang), えいご (bahasa Inggris), ごい (kosakata)" },
  { rate: "N5", kanji: "飯", kunyomi: "めし", onyomi: "はん", meaning_id: "Nasi, makanan", description_id: "Kanji untuk nasi atau makanan, makanan pokok Jepang. Contoh: ごはん (nasi), ちょうしょく (sarapan), はんめし (makanan)" },

  { rate: "N5", kanji: "宅", kunyomi: "-", onyomi: "たく", meaning_id: "Rumah, kediaman", description_id: "Kanji untuk rumah atau kediaman, digunakan dalam alamat formal. Contoh: たく (rumah), じたく (rumah sendiri), たくはい (pengiriman ke rumah)" },
  { rate: "N5", kanji: "客", kunyomi: "-", onyomi: "きゃく、かく", meaning_id: "Tamu", description_id: "Kanji untuk tamu atau pelanggan, penting dalam budaya keramahan Jepang. Contoh: きゃく (tamu), きゃくしつ (kamar tamu), じょうきゃく (penumpang)" },
  { rate: "N5", kanji: "室", kunyomi: "-", onyomi: "しつ", meaning_id: "Ruangan", description_id: "Kanji untuk ruangan, digunakan dalam arsitektur dan tata ruang. Contoh: しつ (ruangan), きょうしつ (kelas), びょうしつ (ruang sakit)" },
  { rate: "N5", kanji: "家", kunyomi: "いえ、や", onyomi: "か、け", meaning_id: "Rumah, keluarga", description_id: "Kanji untuk rumah dan keluarga, konsep fundamental dalam masyarakat Jepang. Contoh: いえ (rumah), かぞく (keluarga), せんもんか (ahli)" },
  { rate: "N5", kanji: "英", kunyomi: "-", onyomi: "えい", meaning_id: "Inggris, unggul", description_id: "Kanji untuk bahasa Inggris dan keunggulan, sering digunakan dalam pendidikan. Contoh: えいご (bahasa Inggris), えいゆう (pahlawan), えいこく (Inggris)" },
  { rate: "N5", kanji: "薬", kunyomi: "くすり", onyomi: "やく", meaning_id: "Obat", description_id: "Kanji untuk obat, penting dalam kesehatan dan pengobatan. Contoh: くすり (obat), やっきょく (apotek), やくざい (obat-obatan)" },
  { rate: "N5", kanji: "会", kunyomi: "あ（う）", onyomi: "かい、え", meaning_id: "Bertemu, pertemuan", description_id: "Kanji untuk bertemu atau organisasi, dasar interaksi sosial. Contoh: あう (bertemu), かいしゃ (perusahaan), かいぎ (rapat)" },
  { rate: "N5", kanji: "今", kunyomi: "いま", onyomi: "こん、きん", meaning_id: "Sekarang", description_id: "Kanji untuk sekarang, sangat penting dalam ekspresi waktu. Contoh: いま (sekarang), こんにち (hari ini), こんや (malam ini)" },
  { rate: "N5", kanji: "雪", kunyomi: "ゆき", onyomi: "せつ", meaning_id: "Salju", description_id: "Kanji untuk salju, penting dalam iklim dan budaya Jepang. Contoh: ゆき (salju), ゆきだるま (boneka salju), おおゆき (salju besar)" },
  { rate: "N5", kanji: "雲", kunyomi: "くも", onyomi: "うん", meaning_id: "Awan", description_id: "Kanji untuk awan, digunakan dalam cuaca dan puisi. Contoh: くも (awan), うんかい (lautan awan), くもり (berawan)" },
  { rate: "N5", kanji: "電", kunyomi: "-", onyomi: "でん", meaning_id: "Listrik", description_id: "Kanji untuk listrik, fundamental dalam teknologi modern. Contoh: でんき (listrik), でんしゃ (kereta), でんわ (telepon)" },
  { rate: "N5", kanji: "売", kunyomi: "う（る）", onyomi: "ばい", meaning_id: "Menjual", description_id: "Kanji untuk menjual, penting dalam perdagangan dan bisnis. Contoh: うる (menjual), はんばい (penjualan), ばいてん (toko)" },

  { rate: "N5", kanji: "広", kunyomi: "ひろ（い）", onyomi: "こう", meaning_id: "Luas", description_id: "Kanji untuk luas atau lebar, digunakan dalam deskripsi ruang. Contoh: ひろい (luas), こうこく (iklan), ひろば (lapangan)" },
  { rate: "N5", kanji: "店", kunyomi: "みせ", onyomi: "てん", meaning_id: "Toko", description_id: "Kanji untuk toko, fundamental dalam aktivitas berbelanja. Contoh: みせ (toko), てんいん (pelayan toko), かいてん (buka toko)" },
  { rate: "N5", kanji: "度", kunyomi: "-", onyomi: "ど、たく", meaning_id: "Derajat, kali", description_id: "Kanji untuk derajat atau kali, digunakan dalam pengukuran dan frekuensi. Contoh: ど (derajat), いちど (sekali), ていど (tingkat)" },
  { rate: "N5", kanji: "病", kunyomi: "やまい", onyomi: "びょう", meaning_id: "Sakit, penyakit", description_id: "Kanji untuk penyakit, penting dalam kesehatan dan medis. Contoh: びょうき (penyakit), びょういん (rumah sakit), びょうにん (pasien)" },
  { rate: "N5", kanji: "疲", kunyomi: "つか（れる）", onyomi: "ひ", meaning_id: "Lelah", description_id: "Kanji untuk lelah, menggambarkan kondisi fisik dan mental. Contoh: つかれる (lelah), ひろう (kelelahan), つかれ (kelelahan)" },
  { rate: "N5", kanji: "痛", kunyomi: "いた（い）", onyomi: "つう", meaning_id: "Sakit, nyeri", description_id: "Kanji untuk sakit atau nyeri, digunakan dalam konteks medis. Contoh: いたい (sakit), ずつう (sakit kepala), ふくつう (sakit perut)" },
  { rate: "N5", kanji: "屋", kunyomi: "や", onyomi: "おく", meaning_id: "Rumah, toko (akhiran)", description_id: "Kanji untuk toko atau rumah, sering digunakan sebagai akhiran nama toko. Contoh: ほんや (toko buku), パンや (toko roti), やね (atap)" },
  { rate: "N5", kanji: "国", kunyomi: "くに", onyomi: "こく、ごく", meaning_id: "Negara", description_id: "Kanji untuk negara, fundamental dalam geografi dan politik. Contoh: くに (negara), がいこく (luar negeri), ちゅうごく (China)" },
  { rate: "N5", kanji: "回", kunyomi: "まわ（る）", onyomi: "かい", meaning_id: "Berputar, kali", description_id: "Kanji untuk putaran atau kali, digunakan dalam frekuensi dan urutan. Contoh: かい (kali), いっかい (satu kali), まわる (berputar)" },
  { rate: "N5", kanji: "困", kunyomi: "こま（る）", onyomi: "こん", meaning_id: "Kesulitan", description_id: "Kanji untuk kesulitan atau masalah, menggambarkan situasi sulit. Contoh: こまる (kesulitan), こんなん (kesulitan), しんこん (kemiskinan)" },
  { rate: "N5", kanji: "開", kunyomi: "あ（く）、ひら（く）", onyomi: "かい", meaning_id: "Membuka", description_id: "Kanji untuk membuka, digunakan dalam aktivitas sehari-hari. Contoh: あく (terbuka), ひらく (membuka), かいてん (buka toko)" },
  { rate: "N5", kanji: "閉", kunyomi: "し（める）、と（じる）", onyomi: "へい", meaning_id: "Menutup", description_id: "Kanji untuk menutup, kebalikan dari 開. Contoh: しまる (tertutup), とじる (menutup), へいてん (tutup toko)" },

  { rate: "N5", kanji: "近", kunyomi: "ちか（い）", onyomi: "きん", meaning_id: "Dekat", description_id: "Kanji untuk dekat, digunakan dalam jarak dan waktu. Contoh: ちかい (dekat), さいきん (baru-baru ini), きんじょ (tetangga)" },
  { rate: "N5", kanji: "遠", kunyomi: "とお（い）", onyomi: "えん", meaning_id: "Jauh", description_id: "Kanji untuk jauh, kebalikan dari 近. Contoh: とおい (jauh), えんきょり (jarak jauh), えんそく (tamasya)" },
  { rate: "N5", kanji: "速", kunyomi: "はや（い）", onyomi: "そく", meaning_id: "Cepat (kecepatan)", description_id: "Kanji untuk cepat, digunakan dalam kecepatan dan waktu. Contoh: はやい (cepat), そくど (kecepatan), こうそく (kecepatan tinggi)" },
  { rate: "N5", kanji: "遅", kunyomi: "おそ（い）、おく（れる）", onyomi: "ち", meaning_id: "Lambat, terlambat", description_id: "Kanji untuk lambat atau terlambat, kebalikan dari 速. Contoh: おそい (lambat), ちこく (terlambat), おくれる (terlambat)" },
  { rate: "N5", kanji: "道", kunyomi: "みち", onyomi: "どう", meaning_id: "Jalan, cara", description_id: "Kanji untuk jalan dan cara, fundamental dalam navigasi dan filosofi. Contoh: みち (jalan), しどう (bimbingan), ぶどう (anggur)" },
  { rate: "N5", kanji: "青", kunyomi: "あお（い）", onyomi: "せい、しょう", meaning_id: "Biru", description_id: "Kanji untuk biru, warna dasar yang sering digunakan. Contoh: あお (biru), あおい (biru), せいしゅん (masa muda)" },
  { rate: "N5", kanji: "晴", kunyomi: "は（れる）", onyomi: "せい", meaning_id: "Cerah", description_id: "Kanji untuk cerah, digunakan dalam cuaca dan suasana hati. Contoh: はれ (cerah), はれる (menjadi cerah), せいてん (cuaca cerah)" },
  { rate: "N5", kanji: "静", kunyomi: "しず（か）", onyomi: "せい、じょう", meaning_id: "Tenang, sunyi", description_id: "Kanji untuk tenang atau sepi, menggambarkan keadaan damai. Contoh: しずか (tenang), せいじゃく (ketenangan), れいせい (tenang)" },
  { rate: "N5", kanji: "寺", kunyomi: "てら", onyomi: "じ", meaning_id: "Kuil", description_id: "Kanji untuk kuil Buddha, penting dalam budaya dan agama Jepang. Contoh: てら (kuil), きんかくじ (Kuil Kinkaku), やくしじ (Kuil Yakushi)" },
  { rate: "N5", kanji: "持", kunyomi: "も（つ）", onyomi: "じ", meaning_id: "Memegang, memiliki", description_id: "Kanji untuk membawa atau memiliki, digunakan dalam kepemilikan. Contoh: もつ (membawa), しじ (dukungan), きもち (perasaan)" },
  { rate: "N5", kanji: "荷", kunyomi: "に", onyomi: "か", meaning_id: "Barang bawaan", description_id: "Kanji untuk barang bawaan, digunakan dalam pengiriman dan transportasi. Contoh: にもつ (barang bawaan), かか (beban), しゅっか (pengiriman)" },
  { rate: "N5", kanji: "歌", kunyomi: "うた、うた（う）", onyomi: "か", meaning_id: "Lagu, menyanyi", description_id: "Kanji untuk lagu atau menyanyi, penting dalam budaya musik Jepang. Contoh: うた (lagu), かし (lirik), しか (penyair)" },

  { rate: "N5", kanji: "友", kunyomi: "とも", onyomi: "ゆう", meaning_id: "Teman", description_id: "Kanji untuk teman, fundamental dalam hubungan sosial. Contoh: とも (teman), ともだち (teman), ゆうじん (sahabat)" },
  { rate: "N5", kanji: "父", kunyomi: "ちち", onyomi: "ふ", meaning_id: "Ayah", description_id: "Kanji untuk ayah, anggota keluarga inti. Contoh: ちち (ayah), おとうさん (ayah), ふぼ (orang tua)" },
  { rate: "N5", kanji: "母", kunyomi: "はは", onyomi: "ぼ", meaning_id: "Ibu", description_id: "Kanji untuk ibu, anggota keluarga inti. Contoh: はは (ibu), おかあさん (ibu), ぼこく (tanah air)" },
  { rate: "N5", kanji: "兄", kunyomi: "あに", onyomi: "けい、きょう", meaning_id: "Kakak laki-laki", description_id: "Kanji untuk kakak laki-laki, hubungan keluarga penting. Contoh: あに (kakak laki-laki), おにいさん (kakak), きょうだい (saudara)" },
  { rate: "N5", kanji: "姉", kunyomi: "あね", onyomi: "し", meaning_id: "Kakak perempuan", description_id: "Kanji untuk kakak perempuan, hubungan keluarga penting. Contoh: あね (kakak perempuan), おねえさん (kakak), しまい (bersaudara perempuan)" },
  { rate: "N5", kanji: "弟", kunyomi: "おとうと", onyomi: "だい、てい", meaning_id: "Adik laki-laki", description_id: "Kanji untuk adik laki-laki, hubungan keluarga penting. Contoh: おとうと (adik laki-laki), でし (murid), きょうだい (saudara)" },
  { rate: "N5", kanji: "妹", kunyomi: "いもうと", onyomi: "まい", meaning_id: "Adik perempuan", description_id: "Kanji untuk adik perempuan, hubungan keluarga penting. Contoh: いもうと (adik perempuan), しまい (bersaudara perempuan), おとうと (adik)" },
  { rate: "N5", kanji: "夫", kunyomi: "おっと", onyomi: "ふ", meaning_id: "Suami", description_id: "Kanji untuk suami, hubungan pernikahan penting. Contoh: おっと (suami), ふうふ (suami istri), ふじん (istri)" },
  { rate: "N5", kanji: "妻", kunyomi: "つま", onyomi: "さい", meaning_id: "Istri", description_id: "Kanji untuk istri, hubungan pernikahan penting. Contoh: つま (istri), さいくん (istri), ふうふ (suami istri)" },
  { rate: "N5", kanji: "彼", kunyomi: "かれ", onyomi: "ひ", meaning_id: "Dia (laki-laki)", description_id: "Kanji untuk dia laki-laki, kata ganti orang ketiga. Contoh: かれ (dia), かれし (pacar), かのじょ (dia perempuan)" },
  { rate: "N5", kanji: "主", kunyomi: "ぬし", onyomi: "しゅ", meaning_id: "Tuan, utama", description_id: "Kanji untuk tuan atau utama, menunjukkan kepemimpinan. Contoh: しゅじん (tuan rumah), おも (utama), しゅやく (peran utama)" },
  { rate: "N5", kanji: "奥", kunyomi: "おく", onyomi: "おう", meaning_id: "Dalam, istri", description_id: "Kanji untuk dalam atau istri, digunakan dalam konteks rumah tangga. Contoh: おく (dalam), おくさん (istri), おくそこ (dasar hati)" },

  { rate: "N5", kanji: "元", kunyomi: "もと", onyomi: "げん、がん", meaning_id: "Asal, dasar", description_id: "Kanji untuk asal atau mantan, digunakan dalam berbagai konteks. Contoh: もと (asal), げんき (sehat), げんそ (unsur)" },
  { rate: "N5", kanji: "気", kunyomi: "き", onyomi: "き、け", meaning_id: "Perasaan, udara", description_id: "Kanji untuk perasaan atau energi, sangat penting dalam ekspresi emosi. Contoh: き (perasaan), げんき (sehat), てんき (cuaca)" },
  { rate: "N5", kanji: "有", kunyomi: "あ（る）", onyomi: "ゆう、う", meaning_id: "Ada, memiliki", description_id: "Kanji untuk ada atau memiliki, digunakan dalam kepemilikan. Contoh: ある (ada), ゆうめい (terkenal), ゆうりょう (berbayar)" },
  { rate: "N5", kanji: "名", kunyomi: "な", onyomi: "めい、みょう", meaning_id: "Nama", description_id: "Kanji untuk nama, fundamental dalam identitas. Contoh: なまえ (nama), ゆうめい (terkenal), めいし (kartu nama)" },
  { rate: "N5", kanji: "親", kunyomi: "おや、した（しい）", onyomi: "しん", meaning_id: "Orang tua, dekat", description_id: "Kanji untuk orang tua atau dekat, hubungan keluarga penting. Contoh: おや (orang tua), しんせつ (baik hati), おやこ (orang tua dan anak)" },
  { rate: "N5", kanji: "切", kunyomi: "き（る）、せつ", onyomi: "せつ、さい", meaning_id: "Memotong, penting", description_id: "Kanji untuk memotong atau penting, digunakan dalam berbagai konteks. Contoh: きる (memotong), たいせつ (penting), しんせつ (baik hati)" },
  { rate: "N5", kanji: "便", kunyomi: "-", onyomi: "べん、びん", meaning_id: "Kemudahan, pos", description_id: "Kanji untuk kemudahan atau surat, digunakan dalam komunikasi. Contoh: びん (surat), べんり (mudah), ふべん (tidak mudah)" },
  { rate: "N5", kanji: "利", kunyomi: "き（く）", onyomi: "り", meaning_id: "Keuntungan, tajam", description_id: "Kanji untuk keuntungan atau mudah, digunakan dalam bisnis. Contoh: りえき (keuntungan), べんり (mudah), りよう (penggunaan)" },
  { rate: "N5", kanji: "不", kunyomi: "-", onyomi: "ふ、ぶ", meaning_id: "Tidak, bukan", description_id: "Kanji untuk tidak atau negatif, digunakan sebagai awalan negatif. Contoh: ふべん (tidak mudah), ふあん (tidak tenang), ふかのう (tidak mungkin)" },
  { rate: "N5", kanji: "若", kunyomi: "わか（い）", onyomi: "じゃく、にゃく", meaning_id: "Muda", description_id: "Kanji untuk muda, menggambarkan usia atau pengalaman. Contoh: わかい (muda), わかもの (orang muda), もしくは (atau)" },
  { rate: "N5", kanji: "早", kunyomi: "はや（い）", onyomi: "そう、さっ", meaning_id: "Cepat (waktu), pagi", description_id: "Kanji untuk cepat atau awal, digunakan dalam waktu. Contoh: はやい (cepat), そうき (awal), はやく (cepat)" },
  { rate: "N5", kanji: "忙", kunyomi: "いそが（しい）", onyomi: "ぼう", meaning_id: "Sibuk", description_id: "Kanji untuk sibuk, menggambarkan aktivitas yang padat. Contoh: いそがしい (sibuk), たぼう (sangat sibuk), きゅうぼう (sangat terburu-buru)" },

  { rate: "N5", kanji: "出", kunyomi: "で（る）、だ（す）", onyomi: "しゅつ", meaning_id: "Keluar, mengeluarkan", description_id: "Kanji untuk keluar, digunakan dalam pergerakan dan aktivitas. Contoh: でる (keluar), しゅっぱつ (berangkat), でぐち (pintu keluar)" },
  { rate: "N5", kanji: "入", kunyomi: "はい（る）、い（れる）", onyomi: "にゅう", meaning_id: "Masuk, memasukkan", description_id: "Kanji untuk masuk, kebalikan dari 出. Contoh: はいる (masuk), にゅうがく (masuk sekolah), いりぐち (pintu masuk)" },
  { rate: "N5", kanji: "乗", kunyomi: "の（る）", onyomi: "じょう", meaning_id: "Naik (kendaraan)", description_id: "Kanji untuk naik kendaraan, digunakan dalam transportasi. Contoh: のる (naik), じょうしゃ (naik kendaraan), のりもの (kendaraan)" },
  { rate: "N5", kanji: "降", kunyomi: "お（りる）、ふ（る）", onyomi: "こう", meaning_id: "Turun, turun (hujan)", description_id: "Kanji untuk turun, kebalikan dari 乗 dalam konteks transportasi. Contoh: おりる (turun), こうう (hujan), げしゃ (turun dari kendaraan)" },
  { rate: "N5", kanji: "着", kunyomi: "き（る）、つ（く）", onyomi: "ちゃく", meaning_id: "Memakai, tiba", description_id: "Kanji untuk tiba atau pakaian, digunakan dalam perjalanan dan fashion. Contoh: つく (tiba), きる (memakai), いふく (pakaian)" },
  { rate: "N5", kanji: "渡", kunyomi: "わた（る）、わた（す）", onyomi: "と", meaning_id: "Menyeberang, menyerahkan", description_id: "Kanji untuk menyeberang, digunakan dalam pergerakan dan navigasi. Contoh: わたる (menyeberang), わたし (saya), ひきわたし (penyerahan)" },
  { rate: "N5", kanji: "通", kunyomi: "とお（る）、かよ（う）", onyomi: "つう", meaning_id: "Lewat, menuju", description_id: "Kanji untuk melewati atau berkomunikasi, digunakan dalam transportasi. Contoh: とおる (melewati), つうがく (pergi sekolah), でんわ (telepon)" },
  { rate: "N5", kanji: "走", kunyomi: "はし（る）", onyomi: "そう", meaning_id: "Berlari", description_id: "Kanji untuk berlari, aktivitas fisik dasar. Contoh: はしる (berlari), そうこう (perjalanan), だっそう (melarikan diri)" },
  { rate: "N5", kanji: "歩", kunyomi: "ある（く）、あゆ（む）", onyomi: "ほ、ぶ", meaning_id: "Berjalan", description_id: "Kanji untuk berjalan, aktivitas fisik dasar. Contoh: あるく (berjalan), さんぽ (jalan-jalan), ほどう (trotoar)" },
  { rate: "N5", kanji: "止", kunyomi: "と（まる）、や（める）", onyomi: "し", meaning_id: "Berhenti", description_id: "Kanji untuk berhenti, digunakan dalam pergerakan dan aktivitas. Contoh: とまる (berhenti), ちゅうし (penghentian), きんし (larangan)" },
  { rate: "N5", kanji: "動", kunyomi: "うご（く）", onyomi: "どう", meaning_id: "Bergerak", description_id: "Kanji untuk bergerak, fundamental dalam aktivitas fisik. Contoh: うごく (bergerak), うんどう (olahraga), どうぶつ (hewan)" },
  { rate: "N5", kanji: "働", kunyomi: "はたら（く）", onyomi: "どう", meaning_id: "Bekerja", description_id: "Kanji untuk bekerja, aktivitas ekonomi penting. Contoh: はたらく (bekerja), ろうどう (tenaga kerja), どうさ (gerakan)" },

  { rate: "N5", kanji: "右", kunyomi: "みぎ", onyomi: "う、ゆう", meaning_id: "Kanan", description_id: "Kanji untuk kanan, arah dasar dalam navigasi. Contoh: みぎ (kanan), うせつ (belok kanan), みぎがわ (sisi kanan)" },
  { rate: "N5", kanji: "左", kunyomi: "ひだり", onyomi: "さ", meaning_id: "Kiri", description_id: "Kanji untuk kiri, arah dasar dalam navigasi. Contoh: ひだり (kiri), させつ (belok kiri), ひだりがわ (sisi kiri)" },
  { rate: "N5", kanji: "東", kunyomi: "ひがし", onyomi: "とう", meaning_id: "Timur", description_id: "Kanji untuk timur, arah mata angin penting. Contoh: ひがし (timur), とうきょう (Tokyo), かんとう (Kanto)" },
  { rate: "N5", kanji: "西", kunyomi: "にし", onyomi: "せい、さい", meaning_id: "Barat", description_id: "Kanji untuk barat, arah mata angin penting. Contoh: にし (barat), かんさい (Kansai), せいよう (Barat)" },
  { rate: "N5", kanji: "北", kunyomi: "きた", onyomi: "ほく", meaning_id: "Utara", description_id: "Kanji untuk utara, arah mata angin penting. Contoh: きた (utara), ほっかいどう (Hokkaido), きたぐち (pintu utara)" },
  { rate: "N5", kanji: "南", kunyomi: "みなみ", onyomi: "なん", meaning_id: "Selatan", description_id: "Kanji untuk selatan, arah mata angin penting. Contoh: みなみ (selatan), みなみぐち (pintu selatan), なんぼく (utara-selatan)" },
  { rate: "N5", kanji: "外", kunyomi: "そと", onyomi: "がい、げ", meaning_id: "Luar", description_id: "Kanji untuk luar, digunakan dalam lokasi dan hubungan. Contoh: そと (luar), がいこく (luar negeri), そとがわ (bagian luar)" },
  { rate: "N5", kanji: "内", kunyomi: "うち", onyomi: "ない", meaning_id: "Dalam", description_id: "Kanji untuk dalam, kebalikan dari 外. Contoh: うち (dalam), あんない (panduan), こくない (dalam negeri)" },
  { rate: "N5", kanji: "部", kunyomi: "-", onyomi: "ぶ", meaning_id: "Bagian, departemen", description_id: "Kanji untuk bagian atau klub, digunakan dalam organisasi. Contoh: ぶぶん (bagian), ぶかつ (klub sekolah), ぜんぶ (semua)" },
  { rate: "N5", kanji: "駅", kunyomi: "-", onyomi: "えき", meaning_id: "Stasiun", description_id: "Kanji untuk stasiun, penting dalam transportasi umum. Contoh: えき (stasiun), えきまえ (depan stasiun), しゅうえき (stasiun terminal)" },
  { rate: "N5", kanji: "社", kunyomi: "やしろ", onyomi: "しゃ", meaning_id: "Perusahaan, kuil", description_id: "Kanji untuk perusahaan atau kuil, digunakan dalam bisnis dan agama. Contoh: かいしゃ (perusahaan), しゃちょう (direktur), じんじゃ (kuil Shinto)" },
  { rate: "N5", kanji: "院", kunyomi: "-", onyomi: "いん", meaning_id: "Institusi, rumah sakit", description_id: "Kanji untuk lembaga atau rumah sakit, digunakan dalam institusi. Contoh: びょういん (rumah sakit), だいがくいん (pascasarjana), ぎいん (anggota parlemen)" },

  { rate: "N5", kanji: "地", kunyomi: "-", onyomi: "ち、じ", meaning_id: "Tanah, daerah", description_id: "Kanji untuk tanah atau daerah, fundamental dalam geografi. Contoh: ち (tanah), じめん (permukaan tanah), ばしょ (tempat)" },
  { rate: "N5", kanji: "鉄", kunyomi: "てつ", onyomi: "てつ", meaning_id: "Besi", description_id: "Kanji untuk besi, digunakan dalam industri dan transportasi. Contoh: てつ (besi), でんしゃ (kereta), てつどう (kereta api)" },
  { rate: "N5", kanji: "工", kunyomi: "-", onyomi: "こう、く", meaning_id: "Industri, pekerjaan", description_id: "Kanji untuk industri atau pekerjaan, digunakan dalam teknik. Contoh: こうじょう (pabrik), こうがく (teknik), だいく (tukang kayu)" },
  { rate: "N5", kanji: "場", kunyomi: "ば", onyomi: "じょう", meaning_id: "Tempat", description_id: "Kanji untuk tempat atau lapangan, digunakan dalam lokasi. Contoh: ばしょ (tempat), こうじょう (pabrik), ばあい (kasus)" },
  { rate: "N5", kanji: "図", kunyomi: "-", onyomi: "ず、と", meaning_id: "Gambar, peta", description_id: "Kanji untuk gambar atau peta, digunakan dalam visual dan dokumen. Contoh: ず (gambar), としょかん (perpustakaan), ちず (peta)" },
  { rate: "N5", kanji: "館", kunyomi: "やかた", onyomi: "かん", meaning_id: "Gedung, balai", description_id: "Kanji untuk gedung atau aula, digunakan dalam bangunan publik. Contoh: としょかん (perpustakaan), びじutsukan (museum seni), たいいくかん (gedung olahraga)" },
  { rate: "N5", kanji: "公", kunyomi: "おおやけ", onyomi: "こう", meaning_id: "Umum, publik", description_id: "Kanji untuk umum atau publik, digunakan dalam layanan masyarakat. Contoh: こうえん (taman), こうきょう (publik), こうむいん (PNS)" },
  { rate: "N5", kanji: "園", kunyomi: "その", onyomi: "えん", meaning_id: "Kebun, taman", description_id: "Kanji untuk kebun atau taman, digunakan dalam lansekap. Contoh: こうえん (taman), ようちえん (TK), どうぶつえん (kebun binatang)" },
  { rate: "N5", kanji: "住", kunyomi: "す（む）", onyomi: "じゅう", meaning_id: "Tinggal", description_id: "Kanji untuk tinggal, digunakan dalam tempat tinggal. Contoh: すむ (tinggal), じゅうしょ (alamat), すまい (rumah)" },
  { rate: "N5", kanji: "所", kunyomi: "ところ", onyomi: "しょ", meaning_id: "Tempat", description_id: "Kanji untuk tempat, digunakan dalam lokasi dan alamat. Contoh: ところ (tempat), じゅうしょ (alamat), ばしょ (tempat)" },
  { rate: "N5", kanji: "番", kunyomi: "-", onyomi: "ばん", meaning_id: "Nomor, giliran", description_id: "Kanji untuk nomor atau urutan, digunakan dalam sistem penomoran. Contoh: ばん (nomor), じゅんばん (urutan), ばんごう (nomor)" },
  { rate: "N5", kanji: "号", kunyomi: "-", onyomi: "ごう", meaning_id: "Nomor, tanda", description_id: "Kanji untuk nomor atau sinyal, digunakan dalam sistem identifikasi. Contoh: ごう (nomor), でんしゃ (kereta), ばんごう (nomor)" },

  { rate: "N5", kanji: "市", kunyomi: "いち", onyomi: "し", meaning_id: "Kota kecil", description_id: "Kanji untuk kota, unit administratif penting. Contoh: し (kota), しみん (warga kota), いちば (pasar)" },
  { rate: "N5", kanji: "町", kunyomi: "まち", onyomi: "ちょう", meaning_id: "Kota besar, pusat kota", description_id: "Kanji untuk kota kecil, unit administratif di bawah kota. Contoh: まち (kota kecil), ちょう (kota), がいとう (lampu jalan)" },
  { rate: "N5", kanji: "村", kunyomi: "むら", onyomi: "そん", meaning_id: "Desa", description_id: "Kanji untuk desa, unit administratif terkecil. Contoh: むら (desa), のうそん (desa pertanian), そんちょう (kepala desa)" },
  { rate: "N5", kanji: "区", kunyomi: "-", onyomi: "く", meaning_id: "Distrik", description_id: "Kanji untuk distrik atau wilayah, pembagian administratif. Contoh: く (distrik), ちく (area), くぶん (pembagian)" },
  { rate: "N5", kanji: "都", kunyomi: "みやこ", onyomi: "と、つ", meaning_id: "Kota Metropolitan, Ibu kota", description_id: "Kanji untuk metropolis, unit administratif tertinggi. Contoh: みやこ (ibu kota), とうきょうと (Tokyo Metropolis), きょうと (Kyoto)" },
  { rate: "N5", kanji: "府", kunyomi: "-", onyomi: "ふ", meaning_id: "Administrasi, Prefektur", description_id: "Kanji untuk prefektur, unit administratif setingkat provinsi. Contoh: ふ (prefektur), せいふ (pemerintah), おおさかふ (Prefektur Osaka)" },
  { rate: "N5", kanji: "県", kunyomi: "-", onyomi: "けん", meaning_id: "Prefektur", description_id: "Kanji untuk prefektur, unit administratif paling umum di Jepang. Contoh: けん (prefektur), けんみん (warga prefektur), あいちけん (Prefektur Aichi)" },
  { rate: "N5", kanji: "島", kunyomi: "しま", onyomi: "とう", meaning_id: "Pulau", description_id: "Kanji untuk pulau, penting sebagai negara kepulauan. Contoh: しま (pulau), はんとう (semenanjung), ひろしま (Hiroshima)" },
  { rate: "N5", kanji: "京", kunyomi: "-", onyomi: "きょう、けい", meaning_id: "Ibu kota", description_id: "Kanji untuk ibu kota, digunakan dalam nama kota besar. Contoh: きょう (ibu kota), とうきょう (Tokyo), きょうと (Kyoto)" },
  { rate: "N5", kanji: "様", kunyomi: "さま", onyomi: "よう", meaning_id: "Situasi, Panggilan Tuan, Nyonya, Nona", description_id: "Kanji untuk cara atau honorifik, digunakan dalam kesopanan. Contoh: よう (cara), さま (tuan/nyonya), どうよう (lagu anak)" },

  { rate: "N5", kanji: "練", kunyomi: "ね（る）", onyomi: "れん", meaning_id: "Berlatih, melatih", description_id: "Kanji untuk latihan, digunakan dalam pengembangan keterampilan. Contoh: れんしゅう (latihan), くんれん (pelatihan), れんしゅうする (berlatih)" },
  { rate: "N5", kanji: "習", kunyomi: "なら（う）", onyomi: "しゅう", meaning_id: "Belajar, kebiasaan", description_id: "Kanji untuk belajar, fundamental dalam pendidikan. Contoh: ならう (belajar), しゅうかん (kebiasaan), れんしゅう (latihan)" },
  { rate: "N5", kanji: "勉", kunyomi: "-", onyomi: "べん", meaning_id: "Rajin, usaha keras", description_id: "Kanji untuk usaha dalam belajar, digunakan dalam pendidikan. Contoh: べんきょう (belajar), べんきょうする (belajar), きんべん (rajin)" },
  { rate: "N5", kanji: "強", kunyomi: "つよ（い）、し（いる）", onyomi: "きょう、ごう", meaning_id: "Kuat, memaksa", description_id: "Kanji untuk kuat, digunakan dalam kekuatan dan intensitas. Contoh: つよい (kuat), べんきょう (belajar), きょうりょく (kerjasama)" },
  { rate: "N5", kanji: "研", kunyomi: "と（ぐ）", onyomi: "けん", meaning_id: "Meneliti, mengasah", description_id: "Kanji untuk penelitian, digunakan dalam akademik dan sains. Contoh: けんきゅう (penelitian), けんきゅうしゃ (peneliti), けんさん (penelitian)" },
  { rate: "N5", kanji: "究", kunyomi: "きわ（める）", onyomi: "きゅう", meaning_id: "Meneliti, mendalami", description_id: "Kanji untuk menyelidiki, digunakan dalam penelitian mendalam. Contoh: けんきゅう (penelitian), きゅうめい (pencerahan), たんきゅう (pencarian)" },
  { rate: "N5", kanji: "留", kunyomi: "と（める）、と（まる）", onyomi: "りゅう", meaning_id: "Menahan, tinggal", description_id: "Kanji untuk tinggal atau menahan, digunakan dalam konteks temporer. Contoh: りゅうがく (belajar di luar negeri), とまる (tinggal), るす (tidak di rumah)" },
  { rate: "N5", kanji: "質", kunyomi: "-", onyomi: "しつ、しち", meaning_id: "Kualitas, sifat", description_id: "Kanji untuk kualitas atau sifat, digunakan dalam evaluasi. Contoh: しつもん (pertanyaan), ひんしつ (kualitas), しつりょう (massa)" },
  { rate: "N5", kanji: "問", kunyomi: "と（う）", onyomi: "もん", meaning_id: "Bertanya, masalah", description_id: "Kanji untuk bertanya, fundamental dalam komunikasi. Contoh: とう (bertanya), しつもん (pertanyaan), もんだい (masalah)" },
  { rate: "N5", kanji: "題", kunyomi: "-", onyomi: "だい", meaning_id: "Topik, masalah", description_id: "Kanji untuk topik atau judul, digunakan dalam penulisan. Contoh: だい (topik), もんだい (masalah), しゅだい (tema)" },
  { rate: "N5", kanji: "答", kunyomi: "こた（える）", onyomi: "とう", meaning_id: "Menjawab", description_id: "Kanji untuk jawaban, respons terhadap pertanyaan. Contoh: こたえ (jawaban), かいとう (jawaban), とうあん (jawaban)" },
  { rate: "N5", kanji: "宿", kunyomi: "やど", onyomi: "しゅく", meaning_id: "Penginapan, PR", description_id: "Kanji untuk penginapan atau PR sekolah, digunakan dalam pendidikan. Contoh: やど (penginapan), しゅくだい (PR), みんしゅく (homestay)" },

  { rate: "N5", kanji: "政", kunyomi: "まつりごと", onyomi: "せい、しょう", meaning_id: "Politik, pemerintahan", description_id: "Kanji untuk politik, digunakan dalam pemerintahan. Contoh: せいじ (politik), せいふ (pemerintah), ぎょうせい (administrasi)" },
  { rate: "N5", kanji: "治", kunyomi: "おさ（める）、なお（る）", onyomi: "じ、ち", meaning_id: "Memerintah, menyembuhkan", description_id: "Kanji untuk mengatur atau menyembuhkan, digunakan dalam pemerintahan dan medis. Contoh: ちりょう (pengobatan), せいじ (politik), じじ (masa kini)" },
  { rate: "N5", kanji: "経", kunyomi: "へ（る）", onyomi: "けい、きょう", meaning_id: "Melalui, ekonomi", description_id: "Kanji untuk melalui atau ekonomi, digunakan dalam bisnis. Contoh: けいざい (ekonomi), けいけん (pengalaman), けいゆ (melalui)" },
  { rate: "N5", kanji: "済", kunyomi: "す（む）", onyomi: "さい", meaning_id: "Selesai, ekonomi", description_id: "Kanji untuk selesai atau ekonomi, digunakan dalam penyelesaian. Contoh: けいざい (ekonomi), かいけつ (penyelesaian), すませる (menyelesaikan)" },
  { rate: "N5", kanji: "歴", kunyomi: "-", onyomi: "れき", meaning_id: "Sejarah, riwayat", description_id: "Kanji untuk sejarah, digunakan dalam pembelajaran masa lalu. Contoh: れきし (sejarah), けいれき (pengalaman), れきだい (berturut-turut)" },
  { rate: "N5", kanji: "史", kunyomi: "-", onyomi: "し", meaning_id: "Sejarah", description_id: "Kanji untuk sejarah, digunakan dalam rekam jejak. Contoh: れきし (sejarah), ししょ (buku sejarah), せかいし (sejarah dunia)" },
  { rate: "N5", kanji: "育", kunyomi: "そだ（つ）、はぐく（む）", onyomi: "いく", meaning_id: "Tumbuh, mendidik", description_id: "Kanji untuk membesarkan atau pendidikan, digunakan dalam perkembangan. Contoh: そだてる (membesarkan), きょういく (pendidikan), たいいく (olahraga)" },
  { rate: "N5", kanji: "化", kunyomi: "ば（ける）", onyomi: "か、け", meaning_id: "Berubah, budaya", description_id: "Kanji untuk perubahan atau budaya, digunakan dalam transformasi. Contoh: へんか (perubahan), ぶんか (budaya), かがく (kimia)" },
  { rate: "N5", kanji: "理", kunyomi: "-", onyomi: "り", meaning_id: "Akal, ilmu", description_id: "Kanji untuk alasan atau sains, digunakan dalam logika. Contoh: りゆう (alasan), かがく (sains), りょうり (memasak)" },
  { rate: "N5", kanji: "科", kunyomi: "-", onyomi: "か", meaning_id: "Mata pelajaran, ilmu", description_id: "Kanji untuk mata pelajaran, digunakan dalam pendidikan dan klasifikasi. Contoh: かがく (sains), がっか (departemen), ないか (penyakit dalam)" },
  { rate: "N5", kanji: "数", kunyomi: "かず、かぞ（える）", onyomi: "すう、す", meaning_id: "Angka, menghitung", description_id: "Kanji untuk angka atau matematika, fundamental dalam perhitungan. Contoh: かず (angka), すうがく (matematika), にんずう (jumlah orang)" },
  { rate: "N5", kanji: "医", kunyomi: "-", onyomi: "い", meaning_id: "Dokter, kedokteran", description_id: "Kanji untuk medis, digunakan dalam bidang kesehatan." }
]

n5_kanji_data.each do |kanji_data|
  kanji = KanjiSingle.find_or_create_by(kanji: kanji_data[:kanji]) do |k|
    k.rate = kanji_data[:rate]
    k.onyomi = kanji_data[:onyomi]
    k.kunyomi = kanji_data[:kunyomi]
    k.meaning_id = kanji_data[:meaning_id]
    k.description_id = kanji_data[:description_id]
  end

  if kanji.persisted?
    puts "✓ Created/Found: #{kanji.kanji} - #{kanji.meaning_id}"
  else
    puts "✗ Failed: #{kanji_data[:kanji]} - #{kanji.errors.full_messages.join(', ')}"
  end
end

puts "\nN5 Kanji seeding completed!"
puts "Total N5 Kanji: #{KanjiSingle.where(rate: 'N5').count}"