# db/seeds.rb

puts "Memulai penambahan/pembaruan data terjemahan Inggris untuk Kanji..."

kanji_data = [
  # --- N5 Kanji Data ---
  { kanji: '日', meaning_en: 'Sun, day', description_en: 'A fundamental kanji frequently used for expressing days, dates, and the sun. Examples: にちようび (Sunday), きょう (today), にほん (Japan)' },
  { kanji: '月', meaning_en: 'Moon, month', description_en: 'Used for calendar months and names of months. Examples: いちがつ (January), げつようび (Monday), こんげつ (this month)' },
  { kanji: '木', meaning_en: 'Tree, wood', description_en: 'Kanji for tree and wood, also used for Thursday. Examples: もくようび (Thursday), きのした (under the tree), もくざい (timber)' },
  { kanji: '山', meaning_en: 'Mountain', description_en: 'Kanji for mountain, often appears in names of mountains and places. Examples: ふじさん (Mount Fuji), やまのぼり (mountain climbing), やまみち (mountain path)' },
  { kanji: '川', meaning_en: 'River', description_en: 'Used for river, often appears in place names. Examples: かわのみず (river water), たながわ (river name), かわべ (riverbank)' },
  { kanji: '田', meaning_en: 'Rice field', description_en: 'Kanji for rice field, often appears in Japanese family names. Examples: たなか (family name), でんしゃ (train - from 電車), たんぼ (rice field)' },
  { kanji: '人', meaning_en: 'Person, human', description_en: 'Fundamental kanji for human, used in many words. Examples: にほんじん (Japanese person), ひとり (one person), だいじん (minister)' },
  { kanji: '口', meaning_en: 'Mouth', description_en: 'Kanji for mouth, also used for opening or entrance. Examples: いりぐち (entrance), でぐち (exit), じんこう (population)' },
  { kanji: '車', meaning_en: 'Car, vehicle', description_en: 'Kanji for wheeled vehicle, very common in transportation. Examples: でんしゃ (train), じどうしゃ (car), しゃりん (wheel)' },
  { kanji: '門', meaning_en: 'Gate, door', description_en: 'Kanji for gate or large door, often appears in place names. Examples: せいもん (main gate), もんばん (gatekeeper), もんだい (problem)' },

  { kanji: '火', meaning_en: 'Fire', description_en: 'Kanji for fire, used for Tuesday and fire-related things. Examples: かようび (Tuesday), かじ (fire), はなび (fireworks)' },
  { kanji: '水', meaning_en: 'Water', description_en: 'Kanji for water, used for Wednesday and various water-related words. Examples: すいようび (Wednesday), みずうみ (lake), すいどう (water supply)' },
  { kanji: '金', meaning_en: 'Gold, money, metal', description_en: 'Kanji for gold and money, also Friday. Examples: きんようび (Friday), おかね (money), きんこ (safe)' },
  { kanji: '土', meaning_en: 'Earth, soil', description_en: 'Kanji for earth/soil, used for Saturday and earth-related things. Examples: どようび (Saturday), つち (soil), こくど (national land)' },
  { kanji: '子', meaning_en: 'Child', description_en: 'Kanji for child, very commonly used. Examples: こども (children), おとこのこ (boy), おんなのこ (girl)' },
  { kanji: '女', meaning_en: 'Woman, female', description_en: 'Kanji for female, used in various words related to women. Examples: じょせい (woman), おんな (female), じょし (girl)' },
  { kanji: '学', meaning_en: 'Study, learning', description_en: 'Fundamental kanji for education and learning. Examples: がっこう (school), だいがく (university), がくせい (student)' },
  { kanji: '生', meaning_en: 'Life, birth, raw', description_en: 'Versatile kanji for life, birth, and students. Examples: せんせい (teacher), がくせい (student), いきもの (living thing)' },
  { kanji: '先', meaning_en: 'Before, ahead', description_en: 'Kanji for before or earlier, often used in polite expressions. Examples: せんせい (teacher), せんぱい (senior), さきに (first)' },
  { kanji: '私', meaning_en: 'I, private', description_en: 'Kanji for "I" in formal and polite forms. Examples: わたし (I), しりつ (private), ししゃ (private person)' },

  { kanji: '一', meaning_en: 'One', description_en: 'The number one, the most basic kanji for counting. Examples: いちにち (one day), いちど (once), いっぽん (one long object)' },
  { kanji: '二', meaning_en: 'Two', description_en: 'The number two, used in counting and dates. Examples: ふつか (second day of the month), にかい (second floor), ふたり (two people)' },
  { kanji: '三', meaning_en: 'Three', description_en: 'The number three, used in counting and time. Examples: みっか (third day of the month), さんじ (three o\'clock), みつ (three items)' },
  { kanji: '四', meaning_en: 'Four', description_en: 'The number four, often avoided due to homonym with "death". Examples: よっか (fourth day of the month), よじ (four o\'clock), しがつ (April)' },
  { kanji: '五', meaning_en: 'Five', description_en: 'The number five, used in counting and time. Examples: いつか (fifth day of the month), ごじ (five o\'clock), ごがつ (May)' },
  { kanji: '六', meaning_en: 'Six', description_en: 'The number six, used in counting and time. Examples: むいか (sixth day of the month), ろくじ (six o\'clock), ろくがつ (June)' },
  { kanji: '七', meaning_en: 'Seven', description_en: 'The number seven, has two common readings. Examples: なのか (seventh day of the month), しちじ (seven o\'clock), しちがつ (July)' },
  { kanji: '八', meaning_en: 'Eight', description_en: 'The number eight, considered a lucky number. Examples: ようか (eighth day of the month), はちじ (eight o\'clock), はちがつ (August)' },
  { kanji: '九', meaning_en: 'Nine', description_en: 'The number nine, often avoided due to homonym with "suffering". Examples: ここのか (ninth day of the month), くじ (nine o\'clock), くがつ (September)' },
  { kanji: '十', meaning_en: 'Ten', description_en: 'The number ten, the basis of the Japanese number system. Examples: とおか (tenth day of the month), じゅうじ (ten o\'clock), じゅうがつ (October)' },
  { kanji: '百', meaning_en: 'Hundred', description_en: 'The number one hundred, used in large numbers. Examples: ひゃくえん (100 yen), さんびゃく (300), ひゃっか (various kinds)' },
  { kanji: '千', meaning_en: 'Thousand', description_en: 'The number one thousand, used in large numbers. Examples: せんえん (1000 yen), さんぜん (3000), せんねん (one thousand years)' },
  { kanji: '万', meaning_en: 'Ten thousand', description_en: 'The number ten thousand, a large unit in the Japanese number system. Examples: いちまんえん (10,000 yen), ばんざい (banzai), まんねん (ten thousand years)' },
  { kanji: '円', meaning_en: 'Yen (currency), circle', description_en: 'Japanese currency and circular shape. Examples: ひゃくえん (100 yen), えんけい (circular shape), まるい (round)' },
  { kanji: '年', meaning_en: 'Year', description_en: 'Kanji for year, very important in expressing time. Examples: らいねん (next year), ことし (this year), ねんれい (age)' },

  { kanji: '上', meaning_en: 'Above, up, ascend', description_en: 'Kanji for above and up, used in various directional contexts. Examples: うえ (above), じょうず (skillful), のぼる (to climb)' },
  { kanji: '下', meaning_en: 'Below, down, descend', description_en: 'Kanji for below and down, opposite of 上. Examples: した (below), げた (geta), さがる (to drop)' },
  { kanji: '中', meaning_en: 'Middle, inside', description_en: 'Kanji for middle and inside, very frequently used. Examples: なか (inside), ちゅうがく (junior high school), にほんちゅう (all over Japan)' },
  { kanji: '大', meaning_en: 'Big, large', description_en: 'Kanji for big, used in various positive words. Examples: おおきい (big), だいがく (university), たいせつ (important)' },
  { kanji: '小', meaning_en: 'Small, little', description_en: 'Kanji for small, opposite of 大. Examples: ちいさい (small), しょうがく (elementary school), こがた (small type)' },
  { kanji: '本', meaning_en: 'Book, origin, counter for long objects', description_en: 'Versatile kanji for book, origin, and counter for long objects. Examples: ほん (book), にほん (Japan), いっぽん (one long object)' },
  { kanji: '半', meaning_en: 'Half', description_en: 'Kanji for half, used in time and size. Examples: はんぶん (half), はんじ (half hour), ぜんはん (first half)' },
  { kanji: '分', meaning_en: 'Part, minute, understand', description_en: 'Kanji for minute and part, very important in time. Examples: いっぷん (one minute), ぶんせき (analysis), はんぶん (half)' },
  { kanji: '力', meaning_en: 'Power, strength', description_en: 'Kanji for physical and mental strength. Examples: ちから (strength), どりょく (effort), のうりょく (ability)' },
  { kanji: '何', meaning_en: 'What', description_en: 'Kanji for "what", a very important interrogative word. Examples: なに (what), なんじ (what time), なんにん (how many people)' },

  { kanji: '明', meaning_en: 'Bright, clear', description_en: 'Kanji for bright and clear, often used in names. Examples: あかるい (bright), せつめい (explanation), あした (tomorrow)' },
  { kanji: '休', meaning_en: 'Rest, holiday', description_en: 'Kanji for rest and holiday. Examples: やすみ (holiday), きゅうけい (break), やすむ (to rest)' },
  { kanji: '体', meaning_en: 'Body', description_en: 'Kanji for body. Examples: からだ (body), たいいく (physical education), ぜんたい (whole)' },
  { kanji: '好', meaning_en: 'Like, good', description_en: 'Kanji for like and fondness. Examples: すき (like), こうき (curiosity), あいこう (affection)' },
  { kanji: '男', meaning_en: 'Man, male', description_en: 'Kanji for man and male. Examples: おとこ (man), だんせい (male), だんし (boy)' },
  { kanji: '林', meaning_en: 'Small forest', description_en: 'Kanji for small forest, often appears in family names. Examples: はやし (small forest), しんりん (forest), こばやし (family name)' },
  { kanji: '森', meaning_en: 'Forest', description_en: 'Kanji for large forest. Examples: もり (forest), しんりん (forest), もりもり (lush)' },
  { kanji: '間', meaning_en: 'Between, interval', description_en: 'Kanji for time and space in between. Examples: あいだ (between), じかん (time), にんげん (human being)' },
  { kanji: '畑', meaning_en: 'Cultivated field', description_en: 'Kanji for dry crop field. Examples: はたけ (field), のうか (farmer), やさい (vegetables)' },
  { kanji: '岩', meaning_en: 'Rock, boulder', description_en: 'Kanji for large rock and reef. Examples: いわ (rock), がんせき (rock), いわば (if I may say so)' },

  { kanji: '目', meaning_en: 'Eye', description_en: 'Kanji for eye and seeing. Examples: め (eye), もくてき (purpose), ちゅうもく (attention)' },
  { kanji: '耳', meaning_en: 'Ear', description_en: 'Kanji for ear and hearing. Examples: みみ (ear), みみざわり (unpleasant to the ear)' },
  { kanji: '手', meaning_en: 'Hand', description_en: 'Kanji for hand and doing. Examples: て (hand), てつだい (help), しゅだん (means)' },
  { kanji: '足', meaning_en: 'Foot, leg, suffice', description_en: 'Kanji for foot/leg and enough. Examples: あし (foot/leg), そくど (speed), まんぞく (satisfaction)' },
  { kanji: '雨', meaning_en: 'Rain', description_en: 'Kanji for rain and weather. Examples: あめ (rain), うてん (bad weather), あまぐも (rain cloud)' },
  { kanji: '竹', meaning_en: 'Bamboo', description_en: 'Kanji for bamboo. Examples: たけ (bamboo), ちくりん (bamboo grove), たけのこ (bamboo shoot)' },
  { kanji: '米', meaning_en: 'Rice, America', description_en: 'Kanji for rice, a staple food in Japan. Examples: こめ (rice), べいこく (America), こめつぶ (grain of rice)' },
  { kanji: '貝', meaning_en: 'Shellfish', description_en: 'Kanji for shellfish, often used in kanji related to money. Examples: かい (shellfish), かいがら (seashell)' },
  { kanji: '石', meaning_en: 'Stone', description_en: 'Kanji for stone and mineral. Examples: いし (stone), せきゆ (petroleum), いしやき (stone-grilled)' },
  { kanji: '糸', meaning_en: 'Thread', description_en: 'Kanji for thread and fabric. Examples: いと (thread), けいと (yarn), ししゅう (embroidery)' },

  { kanji: '花', meaning_en: 'Flower', description_en: 'Kanji for flower and beautiful. Examples: はな (flower), かびん (flower vase), はなみ (flower viewing)' },
  { kanji: '茶', meaning_en: 'Tea', description_en: 'Kanji for tea, an important Japanese culture. Examples: ちゃ (tea), おちゃ (tea), さどう (tea ceremony)' },
  { kanji: '肉', meaning_en: 'Meat', description_en: 'Kanji for meat and muscle. Examples: にく (meat), きんにく (muscle), にくや (butcher shop)' },
  { kanji: '文', meaning_en: 'Sentence, literature', description_en: 'Kanji for writing and literature. Examples: ぶんしょう (sentence), ぶんがく (literature), もんじ (character)' },
  { kanji: '字', meaning_en: 'Character, letter', description_en: 'Kanji for character and letter. Examples: もじ (character/letter), かんじ (kanji), じしょ (dictionary)' },
  { kanji: '物', meaning_en: 'Thing, object', description_en: 'Kanji for thing and object. Examples: もの (thing), どうぶつ (animal), たべもの (food)' },
  { kanji: '牛', meaning_en: 'Cow, cattle', description_en: 'Kanji for cow and cattle. Examples: うし (cow), ぎゅうにく (beef), ぎゅうにゅう (cow\'s milk)' },
  { kanji: '馬', meaning_en: 'Horse', description_en: 'Kanji for horse. Examples: うま (horse), ばしゃ (horse-drawn carriage), じょうば (horse riding)' },
  { kanji: '鳥', meaning_en: 'Bird', description_en: 'Kanji for bird. Examples: とり (bird), やきとり (grilled chicken), にわとり (chicken)' },
  { kanji: '魚', meaning_en: 'Fish', description_en: 'Kanji for fish and seafood. Examples: さかな (fish), きんぎょ (goldfish), さかなや (fish shop)' },

  { kanji: '新', meaning_en: 'New', description_en: 'Kanji for new and fresh. Examples: あたらしい (new), しんぶん (newspaper), しんせん (fresh)' },
  { kanji: '古', meaning_en: 'Old, antique', description_en: 'Kanji for old and antique. Examples: ふるい (old), こだい (ancient times), ちゅうこ (secondhand)' },
  { kanji: '長', meaning_en: 'Long, chief', description_en: 'Kanji for long and leader. Examples: ながい (long), せんせい (teacher), かいちょう (chairman)' },
  { kanji: '短', meaning_en: 'Short', description_en: 'Kanji for short. Examples: みじかい (short), たんじかん (short time), たんぱん (shorts)' },
  { kanji: '高', meaning_en: 'High, expensive', description_en: 'Kanji for high and expensive. Examples: たかい (high/expensive), こうこう (high school), さいこう (highest)' },
  { kanji: '安', meaning_en: 'Cheap, safe', description_en: 'Kanji for cheap and safe. Examples: やすい (cheap), あんぜん (safe), ふあん (unease)' },
  { kanji: '低', meaning_en: 'Low', description_en: 'Kanji for low. Examples: ひくい (low), ていおん (low temperature), さいてい (lowest)' },
  { kanji: '暗', meaning_en: 'Dark', description_en: 'Kanji for dark and gloomy. Examples: くらい (dark), あんき (memorization), やみ (darkness)' },
  { kanji: '多', meaning_en: 'Many, much', description_en: 'Kanji for many and frequent. Examples: おおい (many), たすう (majority), おおく (many)' },
  { kanji: '少', meaning_en: 'Few, little', description_en: 'Kanji for few and young. Examples: すくない (few), しょうねん (boy/youngster), すこし (a little)' },

  { kanji: '行', meaning_en: 'Go, line', description_en: 'Kanji for go and line. Examples: いく (to go), りょこう (travel), ぎんこう (bank)' },
  { kanji: '来', meaning_en: 'Come, next', description_en: 'Kanji for come and next. Examples: くる (to come), らいねん (next year), みらい (future)' },
  { kanji: '帰', meaning_en: 'Return, go home', description_en: 'Kanji for return and go home. Examples: かえる (to go home), きこく (return to one\'s country)' },
  { kanji: '食', meaning_en: 'Eat, food', description_en: 'Kanji for eat and food. Examples: たべる (to eat), しょくじ (meal), しょくりょう (foodstuff)' },
  { kanji: '飲', meaning_en: 'Drink', description_en: 'Kanji for drink. Examples: のむ (to drink), いんりょう (beverage), のみもの (drink)' },
  { kanji: '見', meaning_en: 'See, look', description_en: 'Kanji for see and view. Examples: みる (to see), けんがく (study tour), はっけん (discovery)' },
  { kanji: '聞', meaning_en: 'Hear, listen, ask', description_en: 'Kanji for hear and ask. Examples: きく (to hear), しんぶん (newspaper), うわさ (rumor)' },
  { kanji: '読', meaning_en: 'Read', description_en: 'Kanji for read. Examples: よむ (to read), どくしょ (reading books), どっかい (reading comprehension)' },
  { kanji: '書', meaning_en: 'Write, book', description_en: 'Kanji for write and book. Examples: かく (to write), としょかん (library), しょさい (study room)' },
  { kanji: '話', meaning_en: 'Speak, talk, story', description_en: 'Kanji for speak and story. Examples: はなす (to speak), でんわ (telephone), はなし (story)' },
  { kanji: '買', meaning_en: 'Buy', description_en: 'Kanji for buy. Examples: かう (to buy), かいもの (shopping), こうばい (purchase)' },
  { kanji: '教', meaning_en: 'Teach, instruct', description_en: 'Kanji for teach and religion. Examples: おしえる (to teach), きょうしつ (classroom), しゅうきょう (religion)' },

  { kanji: '朝', meaning_en: 'Morning', description_en: 'Kanji for morning. Examples: あさ (morning), まいあさ (every morning), ちょうしょく (breakfast)' },
  { kanji: '昼', meaning_en: 'Noon, daytime', description_en: 'Kanji for daytime. Examples: ひる (noon), ひるま (daytime), ちゅうしょく (lunch)' },
  { kanji: '夜', meaning_en: 'Night', description_en: 'Kanji for night. Examples: よる (night), まいばん (every night), やしょく (late-night snack)' },
  { kanji: '晩', meaning_en: 'Evening (mealtime)', description_en: 'Kanji for evening. Examples: ばん (evening), ばんごはん (dinner), こんばん (tonight)' },
  { kanji: '夕', meaning_en: 'Dusk, evening', description_en: 'Kanji for dusk and evening. Examples: ゆうがた (evening), ゆうひ (setting sun), ゆうしょく (dinner)' },
  { kanji: '方', meaning_en: 'Direction, way, person', description_en: 'Kanji for direction and way. Examples: かた (way), ほうこう (direction), かたほう (one side)' },
  { kanji: '午', meaning_en: 'Noon', description_en: 'Kanji for noon and time. Examples: ごぜん (AM), ごご (PM), しょうご (noon)' },
  { kanji: '前', meaning_en: 'Front, before', description_en: 'Kanji for front and before. Examples: まえ (front), ぜんかい (previous time), ごぜん (AM)' },
  { kanji: '後', meaning_en: 'Back, after', description_en: 'Kanji for back and after. Examples: あと (after), のち (later), ごご (PM)' },
  { kanji: '毎', meaning_en: 'Every', description_en: 'Kanji for every and always. Examples: まいにち (every day), まいつき (every month), まいしゅう (every week)' },
  { kanji: '週', meaning_en: 'Week', description_en: 'Kanji for week. Examples: しゅう (week), らいしゅう (next week), しゅうまつ (weekend)' },
  { kanji: '曜', meaning_en: 'Day of the week', description_en: 'Kanji for day of the week. Examples: ようび (day), なんようび (what day of the week), どようび (Saturday)' },

  { kanji: '作', meaning_en: 'Make, create, work', description_en: 'Kanji for make or work, often used in creative and work contexts. Examples: さくひん (work), さくしゃ (author), つくる (to make)' },
  { kanji: '泳', meaning_en: 'Swim', description_en: 'Kanji for swim, specifically used in water activities. Examples: すいえい (swimming), およぐ (to swim), へいえい (breaststroke)' },
  { kanji: '油', meaning_en: 'Oil', description_en: 'Kanji for oil, used in cooking and industrial contexts. Examples: あぶら (oil), せきゆ (petroleum), しょうゆ (soy sauce)' },
  { kanji: '海', meaning_en: 'Sea, ocean', description_en: 'Kanji for sea, very important in the geography of Japan as an island nation. Examples: うみ (sea), かいがん (coast), にほんかい (Sea of Japan)' },
  { kanji: '酒', meaning_en: 'Sake, alcohol', description_en: 'Kanji for alcohol, especially traditional Japanese sake. Examples: さけ (sake), びーる (beer), にほんしゅ (Japanese sake)' },
  { kanji: '待', meaning_en: 'Wait', description_en: 'Kanji for wait, often used in daily situations. Examples: まつ (to wait), たいき (waiting), きたい (expectation)' },
  { kanji: '校', meaning_en: 'School', description_en: 'Kanji for school, very important in the education system. Examples: がっこう (school), こうちょう (principal), ぼしこう (mother school)' },
  { kanji: '時', meaning_en: 'Time, hour', description_en: 'Kanji for time and hour, fundamental in daily life. Examples: じかん (time), いちじ (one o\'clock), どうじ (at the same time)' },
  { kanji: '言', meaning_en: 'Say, word', description_en: 'Kanji for say or language, basic communication. Examples: いう (to say), げんご (language), でんごん (message)' },
  { kanji: '計', meaning_en: 'Measure, plan', description_en: 'Kanji for measure or plan, used in mathematics and business. Examples: けいさん (calculation), とけい (clock), けいかく (plan)' },
  { kanji: '語', meaning_en: 'Language, word', description_en: 'Kanji for language or word, often used in language learning. Examples: にほんご (Japanese language), えいご (English language), ごい (vocabulary)' },
  { kanji: '飯', meaning_en: 'Cooked rice, meal', description_en: 'Kanji for rice or meal, a staple food in Japan. Examples: ごはん (cooked rice/meal), ちょうしょく (breakfast), はんめし (meal)' },

  { kanji: '宅', meaning_en: 'Home, residence', description_en: 'Kanji for home or residence, used in formal addresses. Examples: たく (home), じたく (one\'s own home), たくはい (home delivery)' },
  { kanji: '客', meaning_en: 'Guest, customer', description_en: 'Kanji for guest or customer, important in Japanese hospitality culture. Examples: きゃく (guest), きゃくしつ (guest room), じょうきゃく (passenger)' },
  { kanji: '室', meaning_en: 'Room', description_en: 'Kanji for room, used in architecture and space planning. Examples: しつ (room), きょうしつ (classroom), びょうしつ (hospital room)' },
  { kanji: '家', meaning_en: 'House, family', description_en: 'Kanji for house and family, fundamental concepts in Japanese society. Examples: いえ (house), かぞく (family), せんもんか (specialist)' },
  { kanji: '英', meaning_en: 'England, excellence', description_en: 'Kanji for English and excellence, often used in education. Examples: えいご (English language), えいゆう (hero), えいこく (England)' },
  { kanji: '薬', meaning_en: 'Medicine, drug', description_en: 'Kanji for medicine, important in health and treatment. Examples: くすり (medicine), やっきょく (pharmacy), やくざい (medicines)' },
  { kanji: '会', meaning_en: 'Meet, meeting', description_en: 'Kanji for meet or organization, basic social interaction. Examples: あう (to meet), かいしゃ (company), かいぎ (meeting)' },
  { kanji: '今', meaning_en: 'Now', description_en: 'Kanji for now, very important in expressing time. Examples: いま (now), こんにち (today), こんや (tonight)' },
  { kanji: '雪', meaning_en: 'Snow', description_en: 'Kanji for snow, important in Japanese climate and culture. Examples: ゆき (snow), ゆきだるま (snowman), おおゆき (heavy snow)' },
  { kanji: '雲', meaning_en: 'Cloud', description_en: 'Kanji for cloud, used in weather and poetry. Examples: くも (cloud), うんかい (sea of clouds), くもり (cloudy)' },
  { kanji: '電', meaning_en: 'Electricity', description_en: 'Kanji for electricity, fundamental in modern technology. Examples: でんき (electricity), でんしゃ (train), でんわ (telephone)' },
  { kanji: '売', meaning_en: 'Sell', description_en: 'Kanji for sell, important in trade and business. Examples: うる (to sell), はんばい (sales), ばいてん (stand/stall)' },

  { kanji: '広', meaning_en: 'Wide, broad', description_en: 'Kanji for wide or broad, used in spatial descriptions. Examples: ひろい (wide), こうこく (advertisement), ひろば (square)' },
  { kanji: '店', meaning_en: 'Shop, store', description_en: 'Kanji for shop, fundamental in shopping activities. Examples: みせ (shop), てんいん (shop assistant), かいてん (opening a shop)' },
  { kanji: '度', meaning_en: 'Degree, time (frequency)', description_en: 'Kanji for degree or time, used in measurements and frequency. Examples: ど (degree), いちど (once), ていど (degree/level)' },
  { kanji: '病', meaning_en: 'Sick, illness', description_en: 'Kanji for illness, important in health and medicine. Examples: びょうき (illness), びょういん (hospital), びょうにん (patient)' },
  { kanji: '疲', meaning_en: 'Tired', description_en: 'Kanji for tired, describing physical and mental condition. Examples: つかれる (to get tired), ひろう (fatigue), つかれ (tiredness)' },
  { kanji: '痛', meaning_en: 'Pain, ache', description_en: 'Kanji for pain or ache, used in medical contexts. Examples: いたい (painful), ずつう (headache), ふくつう (stomachache)' },
  { kanji: '屋', meaning_en: 'Roof, shop (suffix)', description_en: 'Kanji for shop or house, often used as a suffix for shop names. Examples: ほんや (bookstore), パンや (bakery), やね (roof)' },
  { kanji: '国', meaning_en: 'Country', description_en: 'Kanji for country, fundamental in geography and politics. Examples: くに (country), がいこく (foreign country), ちゅうごく (China)' },
  { kanji: '回', meaning_en: 'Turn, time (frequency)', description_en: 'Kanji for turn or time, used in frequency and order. Examples: かい (time), いっかい (one time), まわる (to turn)' },
  { kanji: '困', meaning_en: 'Trouble, difficulty', description_en: 'Kanji for difficulty or problem, describing a difficult situation. Examples: こまる (to be troubled), こんなん (difficulty), しんこん (poverty)' },
  { kanji: '開', meaning_en: 'Open', description_en: 'Kanji for open, used in daily activities. Examples: あく (to open), ひらく (to open), かいてん (opening of a shop)' },
  { kanji: '閉', meaning_en: 'Close, shut', description_en: 'Kanji for close, opposite of 開. Examples: しまる (to close), とじる (to shut), へいてん (closing of a shop)' },

  { kanji: '近', meaning_en: 'Near, close', description_en: 'Kanji for near, used in distance and time. Examples: ちかい (near), さいきん (recently), きんじょ (neighborhood)' },
  { kanji: '遠', meaning_en: 'Far', description_en: 'Kanji for far, opposite of 近. Examples: とおい (far), えんきょり (long distance), えんそく (excursion)' },
  { kanji: '速', meaning_en: 'Fast (speed)', description_en: 'Kanji for fast, used in speed and time. Examples: はやい (fast), そくど (speed), こうそく (high speed)' },
  { kanji: '遅', meaning_en: 'Slow, late', description_en: 'Kanji for slow or late, opposite of 速. Examples: おそい (slow), ちこく (lateness), おくれる (to be late)' },
  { kanji: '道', meaning_en: 'Way, road, path', description_en: 'Kanji for way and road, fundamental in navigation and philosophy. Examples: みち (road), しどう (guidance), ぶどう (grape)' },
  { kanji: '青', meaning_en: 'Blue', description_en: 'Kanji for blue, a basic color often used. Examples: あお (blue), あおい (blue), せいしゅん (youth)' },
  { kanji: '晴', meaning_en: 'Clear, fine weather', description_en: 'Kanji for clear, used in weather and mood. Examples: はれ (clear weather), はれる (to clear up), せいてん (fine weather)' },
  { kanji: '静', meaning_en: 'Quiet, still', description_en: 'Kanji for quiet or still, describing a peaceful state. Examples: しずか (quiet), せいじゃく (stillness), れいせい (calm)' },
  { kanji: '寺', meaning_en: 'Temple', description_en: 'Kanji for Buddhist temple, important in Japanese culture and religion. Examples: てら (temple), きんかくじ (Kinkaku-ji Temple), やくしじ (Yakushi-ji Temple)' },
  { kanji: '持', meaning_en: 'Hold, have, possess', description_en: 'Kanji for carry or possess, used in ownership. Examples: もつ (to hold), しじ (support), きもち (feeling)' },
  { kanji: '荷', meaning_en: 'Baggage, cargo', description_en: 'Kanji for baggage, used in shipping and transportation. Examples: にもつ (baggage), かか (burden), しゅっか (shipment)' },
  { kanji: '歌', meaning_en: 'Song, sing', description_en: 'Kanji for song or sing, important in Japanese music culture. Examples: うた (song), かし (lyrics), しか (poet)' },

  { kanji: '友', meaning_en: 'Friend', description_en: 'Kanji for friend, fundamental in social relationships. Examples: とも (friend), ともだち (friend), ゆうじん (friend)' },
  { kanji: '父', meaning_en: 'Father', description_en: 'Kanji for father, a core family member. Examples: ちち (my father), おとうさん (father), ふぼ (parents)' },
  { kanji: '母', meaning_en: 'Mother', description_en: 'Kanji for mother, a core family member. Examples: はは (my mother), おかあさん (mother), ぼこく (motherland)' },
  { kanji: '兄', meaning_en: 'Older brother', description_en: 'Kanji for older brother, an important family relationship. Examples: あに (my older brother), おにいさん (older brother), きょうだい (siblings)' },
  { kanji: '姉', meaning_en: 'Older sister', description_en: 'Kanji for older sister, an important family relationship. Examples: あね (my older sister), おねえさん (older sister), しまい (sisters)' },
  { kanji: '弟', meaning_en: 'Younger brother', description_en: 'Kanji for younger brother, an important family relationship. Examples: おとうと (my younger brother), でし (disciple), きょうだい (siblings)' },
  { kanji: '妹', meaning_en: 'Younger sister', description_en: 'Kanji for younger sister, an important family relationship. Examples: いもうと (my younger sister), しまい (sisters), おとうと (younger brother)' },
  { kanji: '夫', meaning_en: 'Husband', description_en: 'Kanji for husband, an important marital relationship. Examples: おっと (my husband), ふうふ (married couple), ふじん (wife)' },
  { kanji: '妻', meaning_en: 'Wife', description_en: 'Kanji for wife, an important marital relationship. Examples: つま (my wife), さいくん (wife), ふうふ (married couple)' },
  { kanji: '彼', meaning_en: 'He, him', description_en: 'Kanji for he/him, a third-person pronoun. Examples: かれ (he), かれし (boyfriend), かのじょ (she)' },
  { kanji: '主', meaning_en: 'Master, chief', description_en: 'Kanji for master or chief, indicating leadership. Examples: しゅじん (master of a house), おも (main), しゅやく (leading role)' },
  { kanji: '奥', meaning_en: 'Interior, wife', description_en: 'Kanji for interior or wife, used in household contexts. Examples: おく (inner part), おくさん (wife), おくそこ (bottom of one\'s heart)' },

  { kanji: '元', meaning_en: 'Origin, former', description_en: 'Kanji for origin or former, used in various contexts. Examples: もと (origin), げんき (healthy), げんそ (element)' },
  { kanji: '気', meaning_en: 'Spirit, air', description_en: 'Kanji for spirit or energy, very important in expressing emotions. Examples: き (spirit/feeling), げんき (healthy), てんき (weather)' },
  { kanji: '有', meaning_en: 'Exist, possess', description_en: 'Kanji for exist or possess, used in ownership. Examples: ある (to exist), ゆうめい (famous), ゆうりょう (paid)' },
  { kanji: '名', meaning_en: 'Name', description_en: 'Kanji for name, fundamental in identity. Examples: なまえ (name), ゆうめい (famous), めいし (business card)' },
  { kanji: '親', meaning_en: 'Parent, intimate', description_en: 'Kanji for parent or intimate, important family relationship. Examples: おや (parent), しんせつ (kindness), おやこ (parent and child)' },
  { kanji: '切', meaning_en: 'Cut, important', description_en: 'Kanji for cut or important, used in various contexts. Examples: きる (to cut), たいせつ (important), しんせつ (kindness)' },
  { kanji: '便', meaning_en: 'Convenience, mail', description_en: 'Kanji for convenience or mail, used in communication. Examples: びん (mail/flight), べんり (convenient), ふべん (inconvenient)' },
  { kanji: '利', meaning_en: 'Profit, advantage', description_en: 'Kanji for profit or advantage, used in business. Examples: りえき (profit), べんり (convenient), りよう (use)' },
  { kanji: '不', meaning_en: 'Not, un-', description_en: 'Kanji for not or negative, used as a negative prefix. Examples: ふべん (inconvenient), ふあん (uneasy), ふかのう (impossible)' },
  { kanji: '若', meaning_en: 'Young', description_en: 'Kanji for young, describing age or experience. Examples: わかい (young), わかもの (young person), もしくは (or)' },
  { kanji: '早', meaning_en: 'Early, fast (time)', description_en: 'Kanji for fast or early, used in time. Examples: はやい (early/fast), そうき (early stage), はやく (quickly)' },
  { kanji: '忙', meaning_en: 'Busy', description_en: 'Kanji for busy, describing a packed schedule. Examples: いそがしい (busy), たぼう (very busy), きゅうぼう (urgency)' },

  { kanji: '出', meaning_en: 'Exit, go out, send out', description_en: 'Kanji for exit, used in movement and activities. Examples: でる (to go out), しゅっぱつ (departure), でぐち (exit)' },
  { kanji: '入', meaning_en: 'Enter, put in', description_en: 'Kanji for enter, opposite of 出. Examples: はいる (to enter), にゅうがく (school entrance), いりぐち (entrance)' },
  { kanji: '乗', meaning_en: 'Ride, board', description_en: 'Kanji for riding a vehicle, used in transportation. Examples: のる (to ride), じょうしゃ (riding a vehicle), のりもの (vehicle)' },
  { kanji: '降', meaning_en: 'Descend, fall (rain)', description_en: 'Kanji for descend, opposite of 乗 in transportation context. Examples: おりる (to get off), こうう (rain), げしゃ (alighting from a vehicle)' },
  { kanji: '着', meaning_en: 'Wear, arrive', description_en: 'Kanji for arrive or clothing, used in travel and fashion. Examples: つく (to arrive), きる (to wear), いふく (clothing)' },
  { kanji: '渡', meaning_en: 'Cross, hand over', description_en: 'Kanji for cross, used in movement and navigation. Examples: わたる (to cross), わたし (I), ひきわたし (handover)' },
  { kanji: '通', meaning_en: 'Pass through, commute', description_en: 'Kanji for pass through or commute, used in transportation. Examples: とおる (to pass through), つうがく (school commute), でんわ (telephone)' },
  { kanji: '走', meaning_en: 'Run', description_en: 'Kanji for run, a basic physical activity. Examples: はしる (to run), そうこう (running), だっそう (escape)' },
  { kanji: '歩', meaning_en: 'Walk', description_en: 'Kanji for walk, a basic physical activity. Examples: あるく (to walk), さんぽ (stroll), ほどう (sidewalk)' },
  { kanji: '止', meaning_en: 'Stop', description_en: 'Kanji for stop, used in movement and activities. Examples: とまる (to stop), ちゅうし (suspension), きんし (prohibition)' },
  { kanji: '動', meaning_en: 'Move', description_en: 'Kanji for move, fundamental in physical activities. Examples: うごく (to move), うんどう (exercise), どうぶつ (animal)' },
  { kanji: '働', meaning_en: 'Work', description_en: 'Kanji for work, an important economic activity. Examples: はたらく (to work), ろうどう (labor), どうさ (action)' },

  { kanji: '右', meaning_en: 'Right', description_en: 'Kanji for right, a basic direction in navigation. Examples: みぎ (right), うせつ (right turn), みぎがわ (right side)' },
  { kanji: '左', meaning_en: 'Left', description_en: 'Kanji for left, a basic direction in navigation. Examples: ひだり (left), させつ (left turn), ひだりがわ (left side)' },
  { kanji: '東', meaning_en: 'East', description_en: 'Kanji for east, an important cardinal direction. Examples: ひがし (east), とうきょう (Tokyo), かんとう (Kanto)' },
  { kanji: '西', meaning_en: 'West', description_en: 'Kanji for west, an important cardinal direction. Examples: にし (west), かんさい (Kansai), せいよう (Western countries)' },
  { kanji: '北', meaning_en: 'North', description_en: 'Kanji for north, an important cardinal direction. Examples: きた (north), ほっかいどう (Hokkaido), きたぐち (north exit)' },
  { kanji: '南', meaning_en: 'South', description_en: 'Kanji for south, an important cardinal direction. Examples: みなみ (south), みなみぐち (south exit), なんぼく (north-south)' },
  { kanji: '外', meaning_en: 'Outside, external', description_en: 'Kanji for outside, used in location and relationships. Examples: そと (outside), がいこく (foreign country), そとがわ (outer side)' },
  { kanji: '内', meaning_en: 'Inside, internal', description_en: 'Kanji for inside, opposite of 外. Examples: うち (inside/home), あんない (guidance), こくない (domestic)' },
  { kanji: '部', meaning_en: 'Part, department', description_en: 'Kanji for part or club, used in organizations. Examples: ぶぶん (part), ぶかつ (club activities), ぜんぶ (all)' },
  { kanji: '駅', meaning_en: 'Station', description_en: 'Kanji for station, important in public transportation. Examples: えき (station), えきまえ (in front of the station), しゅうえき (terminal station)' },
  { kanji: '社', meaning_en: 'Company, shrine', description_en: 'Kanji for company or shrine, used in business and religion. Examples: かいしゃ (company), しゃちょう (company president), じんじゃ (Shinto shrine)' },
  { kanji: '院', meaning_en: 'Institution, hospital', description_en: 'Kanji for institution or hospital, used in institutions. Examples: びょういん (hospital), だいがくいん (graduate school), ぎいん (Diet member)' },

  { kanji: '地', meaning_en: 'Ground, area', description_en: 'Kanji for ground or area, fundamental in geography. Examples: ち (ground), じめん (ground surface), ばしょ (place)' },
  { kanji: '鉄', meaning_en: 'Iron', description_en: 'Kanji for iron, used in industry and transportation. Examples: てつ (iron), でんしゃ (train), てつどう (railway)' },
  { kanji: '工', meaning_en: 'Craft, construction', description_en: 'Kanji for craft or construction, used in engineering. Examples: こうじょう (factory), こうがく (engineering), だいく (carpenter)' },
  { kanji: '場', meaning_en: 'Place, location', description_en: 'Kanji for place or location, used in locations. Examples: ばしょ (place), こうじょう (factory), ばあい (case)' },
  { kanji: '図', meaning_en: 'Drawing, map', description_en: 'Kanji for drawing or map, used in visuals and documents. Examples: ず (drawing), としょかん (library), ちず (map)' },
  { kanji: '館', meaning_en: 'Building, hall', description_en: 'Kanji for building or hall, used in public buildings. Examples: としょかん (library), びじゅつかん (art museum), たいいくかん (gymnasium)' },
  { kanji: '公', meaning_en: 'Public, open', description_en: 'Kanji for public or open, used in public services. Examples: こうえん (park), こうきょう (public), こうむいん (public servant)' },
  { kanji: '園', meaning_en: 'Garden, park', description_en: 'Kanji for garden or park, used in landscaping. Examples: こうえん (park), ようちえん (kindergarten), どうぶつえん (zoo)' },
  { kanji: '住', meaning_en: 'Live, reside', description_en: 'Kanji for live, used in place of residence. Examples: すむ (to live), じゅうしょ (address), すまい (dwelling)' },
  { kanji: '所', meaning_en: 'Place', description_en: 'Kanji for place, used in location and address. Examples: ところ (place), じゅうしょ (address), ばしょ (place)' },
  { kanji: '番', meaning_en: 'Number, turn', description_en: 'Kanji for number or turn, used in numbering systems. Examples: ばん (number), じゅんばん (order), ばんごう (number)' },
  { kanji: '号', meaning_en: 'Number, sign', description_en: 'Kanji for number or sign, used in identification systems. Examples: ごう (number), でんしゃ (train), ばんごう (number)' },

  { kanji: '市', meaning_en: 'City', description_en: 'Kanji for city, an important administrative unit. Examples: し (city), しみん (citizen), いちば (market)' },
  { kanji: '町', meaning_en: 'Town, street', description_en: 'Kanji for town, an administrative unit below a city. Examples: まち (town), ちょう (town), がいとう (street light)' },
  { kanji: '村', meaning_en: 'Village', description_en: 'Kanji for village, the smallest administrative unit. Examples: むら (village), のうそん (farming village), そんちょう (village head)' },
  { kanji: '区', meaning_en: 'Ward, district', description_en: 'Kanji for ward or district, an administrative division. Examples: く (ward/district), ちく (area), くぶん (division)' },
  { kanji: '都', meaning_en: 'Metropolis, capital', description_en: 'Kanji for metropolis, the highest administrative unit. Examples: みやこ (capital city), とうきょうと (Tokyo Metropolis), きょうと (Kyoto)' },
  { kanji: '府', meaning_en: 'Prefecture, government', description_en: 'Kanji for prefecture, a province-level administrative unit. Examples: ふ (prefecture), せいふ (government), おおさかふ (Osaka Prefecture)' },
  { kanji: '県', meaning_en: 'Prefecture', description_en: 'Kanji for prefecture, the most common administrative unit in Japan. Examples: けん (prefecture), けんみん (prefectural resident), あいちけん (Aichi Prefecture)' },
  { kanji: '島', meaning_en: 'Island', description_en: 'Kanji for island, important for an island nation. Examples: しま (island), はんとう (peninsula), ひろしま (Hiroshima)' },
  { kanji: '京', meaning_en: 'Capital', description_en: 'Kanji for capital city, used in names of large cities. Examples: きょう (capital), とうきょう (Tokyo), きょうと (Kyoto)' },
  { kanji: '様', meaning_en: 'Manner, honorific suffix', description_en: 'Kanji for manner or honorific, used in politeness. Examples: よう (manner), さま (Mr./Ms./Mrs.), どうよう (children\'s song)' },

  { kanji: '練', meaning_en: 'Practice, train', description_en: 'Kanji for practice, used in skill development. Examples: れんしゅう (practice), くんれん (training), れんしゅうする (to practice)' },
  { kanji: '習', meaning_en: 'Learn, custom', description_en: 'Kanji for learn, fundamental in education. Examples: ならう (to learn), しゅうかん (habit), れんしゅう (practice)' },
  { kanji: '勉', meaning_en: 'Exertion, diligence', description_en: 'Kanji for exertion in study, used in education. Examples: べんきょう (study), べんきょうする (to study), きんべん (diligence)' },
  { kanji: '強', meaning_en: 'Strong, force', description_en: 'Kanji for strong, used in strength and intensity. Examples: つよい (strong), べんきょう (study), きょうりょく (cooperation)' },
  { kanji: '研', meaning_en: 'Research, sharpen', description_en: 'Kanji for research, used in academia and science. Examples: けんきゅう (research), けんきゅうしゃ (researcher), けんさん (study)' },
  { kanji: '究', meaning_en: 'Research, delve into', description_en: 'Kanji for investigate, used in in-depth research. Examples: けんきゅう (research), きゅうめい (clarification), たんきゅう (inquiry)' },
  { kanji: '留', meaning_en: 'Detain, stay', description_en: 'Kanji for stay or detain, used in temporary contexts. Examples: りゅうがく (study abroad), とまる (to stay), るす (absence from home)' },
  { kanji: '質', meaning_en: 'Quality, nature', description_en: 'Kanji for quality or nature, used in evaluation. Examples: しつもん (question), ひんしつ (quality), しつりょう (mass)' },
  { kanji: '問', meaning_en: 'Ask, question, problem', description_en: 'Kanji for ask, fundamental in communication. Examples: とう (to ask), しつもん (question), もんだい (problem)' },
  { kanji: '題', meaning_en: 'Topic, subject', description_en: 'Kanji for topic or title, used in writing. Examples: だい (topic), もんだい (problem), しゅだい (theme)' },
  { kanji: '答', meaning_en: 'Answer', description_en: 'Kanji for answer, a response to a question. Examples: こたえ (answer), かいとう (answer), とうあん (answer sheet)' },
  { kanji: '宿', meaning_en: 'Inn, lodging, homework', description_en: 'Kanji for lodging or school homework, used in education. Examples: やど (inn), しゅくだい (homework), みんしゅく (minshuku/private lodging)' },

  { kanji: '政', meaning_en: 'Politics, government', description_en: 'Kanji for politics, used in government. Examples: せいじ (politics), せいふ (government), ぎょうせい (administration)' },
  { kanji: '治', meaning_en: 'Govern, cure', description_en: 'Kanji for govern or cure, used in government and medicine. Examples: ちりょう (treatment), せいじ (politics), じじ (current affairs)' },
  { kanji: '経', meaning_en: 'Pass through, economics', description_en: 'Kanji for pass through or economics, used in business. Examples: けいざい (economy), けいけん (experience), けいゆ (via)' },
  { kanji: '済', meaning_en: 'Finish, economy', description_en: 'Kanji for finish or economy, used in completion. Examples: けいざい (economy), かいけつ (solution), すませる (to finish)' },
  { kanji: '歴', meaning_en: 'History, past', description_en: 'Kanji for history, used in learning about the past. Examples: れきし (history), けいれき (personal history), れきだい (successive generations)' },
  { kanji: '史', meaning_en: 'History', description_en: 'Kanji for history, used in records. Examples: れきし (history), ししょ (history book), せかいし (world history)' },
  { kanji: '育', meaning_en: 'Grow, raise, educate', description_en: 'Kanji for raise or education, used in development. Examples: そだてる (to raise), きょういく (education), たいいく (physical education)' },
  { kanji: '化', meaning_en: 'Change, transform, culture', description_en: 'Kanji for change or culture, used in transformation. Examples: へんか (change), ぶんか (culture), かがく (chemistry)' },
  { kanji: '理', meaning_en: 'Reason, logic, science', description_en: 'Kanji for reason or science, used in logic. Examples: りゆう (reason), かがく (science), りょうり (cooking)' },
  { kanji: '科', meaning_en: 'Department, subject', description_en: 'Kanji for subject, used in education and classification. Examples: かがく (science), がっか (department), ないか (internal medicine)' },
  { kanji: '数', meaning_en: 'Number, count', description_en: 'Kanji for number or mathematics, fundamental in calculation. Examples: かず (number), すうがく (mathematics), にんずう (number of people)' },
  { kanji: '医', meaning_en: 'Doctor, medicine', description_en: 'Kanji for medical, used in the healthcare field. Examples: いしゃ (doctor), いがく (medicine, medical science), びょういん (hospital)' }
]

kanji_data.each do |data|
  # Mencari Kanji berdasarkan karakter (asumsi 'kanji' adalah kolom karakter Kanji di DB Anda)
  # Jika tidak ditemukan, akan dibuat entri baru, meskipun seharusnya sudah ada
  kanji_entry = KanjiSingle.find_by(kanji: data[:kanji])

  if kanji_entry
    # Memperbarui hanya kolom meaning_en dan description_en
    # Pastikan Anda tidak secara tidak sengaja mengubah kolom lain
    kanji_entry.update!(
      meaning_en: data[:meaning_en],
      description_en: data[:description_en]
    )
    puts "Diperbarui Kanji: #{data[:kanji]}"
  else
    puts "Kanji: #{data[:kanji]} tidak ditemukan di database. Melewatkan pembaruan."
    # Opsional: Anda bisa memilih untuk membuat entri baru jika Kanji tidak ada
    # Kanji.create!(data)
    # puts "Dibuat Kanji baru: #{data[:kanji]}"
  end
rescue ActiveRecord::RecordInvalid => e
  puts "Gagal memperbarui Kanji #{data[:kanji]}: #{e.message}"
end

puts "Selesai penambahan/pembaruan data terjemahan Inggris untuk Kanji."